"""Single entry point for retrain.

Usage:
    retrain                  # loads retrain.toml from cwd
    retrain config.toml      # single training run
    retrain campaign.toml    # campaign (if TOML has [campaign] section)
    retrain backends         # list backend capabilities/schema metadata
    retrain init             # generate a starter retrain.toml
    retrain doctor           # check installed dependencies for all components
    retrain migrate-config config.toml   # migrate legacy backend keys
    retrain man              # human/agent-friendly manual
    retrain --seed 42 --lr 1e-4   # override config values from CLI

A TOML with a [campaign] section runs multiple conditions × seeds.
A TOML without it runs a single training job. Same command either way.
"""

from __future__ import annotations

import difflib
import json
import os
import re
import sys
import tomllib
from pathlib import Path
from typing import TYPE_CHECKING, cast

from retrain.commands import manual as manual_command
from retrain.commands.name import resolve as resolve_cli_name
from retrain.commands.top import print_help

if TYPE_CHECKING:
    from retrain.config import TrainConfig


_STARTER_TOML = """\
# retrain configuration — generated by `retrain init`
# Docs: docs/configuration.md

[model]
model = "Qwen/Qwen3-4B-Instruct-2507"
lora_rank = 32

[algorithm]
advantage_mode = "maxrl"     # grpo | maxrl | reinforce_pp | my_module.my_advantage
transform_mode = "gtpo_sepa" # none | gtpo | ... | my_module.make_transform_spec

[training]
seed = -1                    # -1 = no seed
max_steps = 100              # conservative default for first run
batch_size = 4               # conservative default for first run
group_size = 16
max_tokens = 10240
temperature = 0.7
lr = 4e-5
save_every = 20

[backend]
backend = "local"
adapter_path = "adapters/my_run"

[logging]
log_dir = "logs/train"
# wandb_project = ""         # uncomment to enable wandb
"""


_QUICKSTART_TOML = """\
# retrain quickstart — 20-step smoke test
# Generated by `retrain init --template quickstart`

[model]
model = "Qwen/Qwen3-4B-Instruct-2507"
lora_rank = 32

[algorithm]
advantage_mode = "grpo"
transform_mode = "none"

[training]
seed = -1
max_steps = 20
batch_size = 2
group_size = 8
max_tokens = 1024            # smoke-test profile (non-default)
temperature = 0.7
lr = 4e-5
save_every = 0               # no checkpoints for a quick test

[backend]
backend = "local"
adapter_path = "adapters/quickstart"

[logging]
log_dir = "logs/quickstart"
"""

_EXPERIMENT_TOML = """\
# retrain experiment — reproducible 500-step training run
# Generated by `retrain init --template experiment`

[model]
model = "Qwen/Qwen3-4B-Instruct-2507"
lora_rank = 32

[algorithm]
advantage_mode = "maxrl"
transform_mode = "gtpo_sepa"

[training]
seed = 42
max_steps = 500
batch_size = 8
group_size = 16
max_tokens = 10240
temperature = 0.7
lr = 4e-5
save_every = 50

[sepa]
steps = 500
schedule = "linear"
delay_steps = 50
correct_rate_gate = 0.1

[backend]
backend = "local"
adapter_path = "adapters/experiment"

[logging]
log_dir = "logs/experiment"
wandb_project = ""           # set your project name to enable wandb
"""

_CAMPAIGN_TOML = """\
# retrain campaign — sweep across conditions and seeds
# Generated by `retrain init --template campaign`

[campaign]
seeds = [42, 101, 202, 303]
max_steps = 200

[[campaign.conditions]]
advantage_mode = "grpo"
transform_mode = "none"

[[campaign.conditions]]
advantage_mode = "maxrl"
transform_mode = "gtpo_sepa"

# Base config shared by all runs
[model]
model = "Qwen/Qwen3-4B-Instruct-2507"
lora_rank = 32

[training]
batch_size = 8
group_size = 16
max_tokens = 10240
temperature = 0.7
lr = 4e-5

[backend]
backend = "local"
adapter_path = "adapters/campaign"

[logging]
log_dir = "logs/campaign"
# wandb_project = ""         # uncomment to enable wandb
"""

# name -> (content, filename)
_INIT_TEMPLATES: dict[str, tuple[str, str]] = {
    "default": (_STARTER_TOML, "retrain.toml"),
    "quickstart": (_QUICKSTART_TOML, "retrain.toml"),
    "experiment": (_EXPERIMENT_TOML, "retrain.toml"),
    "campaign": (_CAMPAIGN_TOML, "campaign.toml"),
}


def _manual_path() -> Path:
    """Location of the editable bundled manual file."""
    return Path(__file__).with_name("retrain.man")


def _customize_toml(
    content: str,
    max_steps: int | None = None,
    seed: int | None = None,
    wandb_project: str | None = None,
) -> str:
    """Apply customizations to a TOML template string via regex."""
    if max_steps is not None:
        content = re.sub(r"^(max_steps\s*=\s*)\d+", rf"\g<1>{max_steps}", content, flags=re.MULTILINE)
    if seed is not None:
        content = re.sub(r"^(seed\s*=\s*)-?\d+", rf"\g<1>{seed}", content, flags=re.MULTILINE)
    if wandb_project is not None:
        if wandb_project:
            # Uncomment and set
            content = re.sub(
                r"^#\s*wandb_project\s*=.*$",
                f'wandb_project = "{wandb_project}"',
                content,
                flags=re.MULTILINE,
            )
            # Replace already-uncommented line
            content = re.sub(
                r'^wandb_project\s*=\s*"[^"]*"',
                f'wandb_project = "{wandb_project}"',
                content,
                flags=re.MULTILINE,
            )
        # Empty string: leave as-is (commented or empty)
    return content


_INTERACTIVE_GOALS: dict[str, tuple[str, int]] = {
    "1": ("quickstart", 20),
    "2": ("experiment", 500),
    "3": ("campaign", 200),
}


def _run_init_interactive(cli_name: str) -> None:
    """Interactively build a retrain config file."""
    if not sys.stdin.isatty():
        print("Interactive init requires a terminal (TTY).", file=sys.stderr)
        sys.exit(1)

    print(f"{cli_name} init — interactive setup\n")
    print("What would you like to do?")
    print("  1) quickstart  — 20-step smoke test")
    print("  2) experiment  — reproducible training run")
    print("  3) campaign    — sweep across conditions and seeds")
    choice = input("\nChoice [1]: ").strip() or "1"
    if choice not in _INTERACTIVE_GOALS:
        print(f"Invalid choice '{choice}'. Using quickstart.", file=sys.stderr)
        choice = "1"

    goal_name, default_steps = _INTERACTIVE_GOALS[choice]

    # Steps
    steps_input = input(f"Training steps [{default_steps}]: ").strip()
    if steps_input:
        try:
            max_steps = int(steps_input)
        except ValueError:
            print(f"Not a number, using default ({default_steps}).", file=sys.stderr)
            max_steps = default_steps
    else:
        max_steps = default_steps

    # Seed
    seed_input = input("Reproducible seed [42]: ").strip()
    if seed_input:
        try:
            seed = int(seed_input)
        except ValueError:
            print("Not a number, using default (42).", file=sys.stderr)
            seed = 42
    else:
        seed = 42

    # Wandb
    wandb_project = input("Wandb project name (empty to skip): ").strip()

    content, filename = _INIT_TEMPLATES[goal_name]
    content = _customize_toml(content, max_steps=max_steps, seed=seed, wandb_project=wandb_project or None)

    dest = Path(filename)
    if dest.exists():
        print(f"{filename} already exists — refusing to overwrite.")
        sys.exit(1)
    dest.write_text(content)
    print(f"\nCreated {filename} (template: {goal_name})")
    print(f"Edit it, then run: {cli_name}")


def _run_init(args: list[str] | None = None, cli_name: str | None = None) -> None:
    """Generate a starter config file in the current directory."""
    if not cli_name:
        cli_name = resolve_cli_name()
    args = args or []

    template_name = "default"
    list_templates = False
    interactive = False
    i = 0
    while i < len(args):
        arg = args[i]
        if arg in ("--interactive", "-i"):
            interactive = True
        elif arg in ("--list", "-l"):
            list_templates = True
        elif arg in ("--template", "-t"):
            i += 1
            if i >= len(args):
                print("Flag --template requires a value.", file=sys.stderr)
                sys.exit(1)
            template_name = args[i]
        elif arg.startswith("--template="):
            template_name = arg.split("=", 1)[1]
        else:
            print(f"Unknown init flag: {arg}", file=sys.stderr)
            sys.exit(1)
        i += 1

    if list_templates:
        print("Available templates:")
        for name, (_, filename) in sorted(_INIT_TEMPLATES.items()):
            print(f"  {name:12s} -> {filename}")
        return

    if interactive:
        _run_init_interactive(cli_name)
        return

    if template_name not in _INIT_TEMPLATES:
        print(
            f"Unknown template '{template_name}'. "
            f"Available: {sorted(_INIT_TEMPLATES)}",
            file=sys.stderr,
        )
        sys.exit(1)

    content, filename = _INIT_TEMPLATES[template_name]
    dest = Path(filename)
    if dest.exists():
        print(f"{filename} already exists — refusing to overwrite.")
        sys.exit(1)
    dest.write_text(content)
    print(f"Created {filename} (template: {template_name})")
    print(f"Edit it, then run: {cli_name}")
    print(f"Need guidance? Run: {cli_name} man")


_PLUGIN_KINDS = {
    "transform",
    "advantage",
    "algorithm",
    "reward",
    "planning",
    "data",
    "backend",
    "inference",
    "backpressure",
    "trainer",
}


def _object_dict(value: object, name: str) -> dict[str, object]:
    if not isinstance(value, dict) or not all(isinstance(key, str) for key in value):
        raise ValueError(f"Invalid {name}: expected object mapping")
    return cast(dict[str, object], value)


def _object_list(value: object, name: str) -> list[dict[str, object]]:
    if not isinstance(value, list):
        raise ValueError(f"Invalid {name}: expected list")
    rows: list[dict[str, object]] = []
    for idx, item in enumerate(value):
        rows.append(_object_dict(item, f"{name}[{idx}]"))
    return rows


def _string_list(value: object, name: str) -> list[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ValueError(f"Invalid {name}: expected list of strings")
    return cast(list[str], value)


def _sanitize_identifier(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", name.strip())
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    if not cleaned:
        return "my_plugin"
    if cleaned[0].isdigit():
        cleaned = f"plugin_{cleaned}"
    return cleaned


def _plugin_template(kind: str, fn_name: str) -> tuple[str, str]:
    """Return (module_content, toml_snippet) for plugin scaffolding."""
    if kind == "transform":
        return (
            (
                "from retrain import TransformOutput\n\n"
                f"def {fn_name}(ctx):\n"
                "    \"\"\"ctx contains episode_advantages/logprobs/planning masks/params.\"\"\"\n"
                "    token_advs = []\n"
                "    for i, logprobs in enumerate(ctx.logprobs_G):\n"
                "        adv = ctx.episode_advantages[i]\n"
                "        token_advs.append([adv for _ in logprobs])\n"
                "    return TransformOutput(\n"
                "        token_advs=token_advs,\n"
                "        has_stats=False,\n"
                "        needs_planning=False,\n"
                "        uses_sepa_controller=False,\n"
                "    )\n"
            ),
            (
                "[algorithm]\n"
                f'transform_mode = "plugins.{fn_name}.{fn_name}"\n'
                "\n[algorithm.transform_params]\n"
                "scale = 1.0\n"
            ),
        )
    if kind == "advantage":
        return (
            (
                f"def {fn_name}(rewards, params=None):\n"
                "    \"\"\"Return one advantage per reward.\"\"\"\n"
                "    if not rewards:\n"
                "        return []\n"
                "    scale = float((params or {}).get('scale', 1.0))\n"
                "    mean_r = sum(rewards) / len(rewards)\n"
                "    return [scale * (r - mean_r) for r in rewards]\n"
            ),
            (
                "[algorithm]\n"
                f'advantage_mode = "plugins.{fn_name}.{fn_name}"\n'
                "\n[algorithm.advantage_params]\n"
                "scale = 2.0\n"
            ),
        )
    if kind == "algorithm":
        return (
            (
                "from retrain import AlgorithmOutput\n\n"
                f"def {fn_name}(ctx):\n"
                "    \"\"\"Full algorithm hook: return token-level advantages directly.\"\"\"\n"
                "    token_advs = []\n"
                "    for rewards_idx, logprobs in enumerate(ctx.logprobs_G):\n"
                "        reward = ctx.rewards_G[rewards_idx]\n"
                "        token_advs.append([reward for _ in logprobs])\n"
                "    return AlgorithmOutput(token_advs=token_advs, has_stats=False)\n"
            ),
            (
                "[algorithm]\n"
                f'algorithm_mode = "plugins.{fn_name}.{fn_name}"\n'
                "\n[algorithm.params]\n"
                "alpha = 0.1\n"
            ),
        )
    if kind == "reward":
        return (
            (
                f"class {fn_name.title().replace('_', '')}Reward:\n"
                "    def score(self, response: str, reference: str) -> float:\n"
                "        return float(response.strip() == reference.strip())\n\n"
                f"def {fn_name}(config):\n"
                f"    return {fn_name.title().replace('_', '')}Reward()\n"
            ),
            (
                "[reward]\n"
                'type = "custom"\n'
                f'custom_module = "plugins.{fn_name}"\n'
                f'custom_function = "{fn_name}"\n'
            ),
        )

    if kind == "trainer":
        return (
            (
                f"def {fn_name}(config):\n"
                '    """Run training. Return adapter path or None.\n\n'
                "    config: retrain.config.TrainConfig\n"
                "    Expected output:\n"
                "      - metrics.jsonl in config.log_dir (for retrain status)\n"
                "      - adapter at config.adapter_path (for downstream use)\n"
                '    """\n'
                "    raise NotImplementedError\n"
            ),
            (
                "[training]\n"
                f'trainer = "plugins.{fn_name}.{fn_name}"\n'
            ),
        )

    generic = (
        f"def {fn_name}(config):\n"
        f"    raise NotImplementedError(\"Implement {kind} plugin contract here.\")\n"
    )
    return (
        generic,
        f"# Use dotted plugin path: plugins.{fn_name}.{fn_name}\n",
    )


def _run_init_plugin(args: list[str], cli_name: str | None = None) -> None:
    """Scaffold a plugin module for students."""
    if not cli_name:
        cli_name = resolve_cli_name()
    kind = ""
    name = ""
    output_dir = "plugins"
    with_test = False

    i = 0
    while i < len(args):
        arg = args[i]
        if arg == "--with-test":
            with_test = True
        elif arg in ("--kind", "-k"):
            i += 1
            if i >= len(args):
                print("Flag --kind requires a value.", file=sys.stderr)
                sys.exit(1)
            kind = args[i].strip().lower()
        elif arg.startswith("--kind="):
            kind = arg.split("=", 1)[1].strip().lower()
        elif arg in ("--name", "-n"):
            i += 1
            if i >= len(args):
                print("Flag --name requires a value.", file=sys.stderr)
                sys.exit(1)
            name = args[i].strip()
        elif arg.startswith("--name="):
            name = arg.split("=", 1)[1].strip()
        elif arg in ("--output-dir", "-o"):
            i += 1
            if i >= len(args):
                print("Flag --output-dir requires a value.", file=sys.stderr)
                sys.exit(1)
            output_dir = args[i].strip()
        elif arg.startswith("--output-dir="):
            output_dir = arg.split("=", 1)[1].strip()
        else:
            print(f"Unknown init-plugin flag: {arg}", file=sys.stderr)
            sys.exit(1)
        i += 1

    if kind not in _PLUGIN_KINDS:
        print(
            f"Invalid --kind '{kind}'. "
            f"Choose one of: {sorted(_PLUGIN_KINDS)}",
            file=sys.stderr,
        )
        sys.exit(1)
    if not name:
        print("Flag --name is required.", file=sys.stderr)
        sys.exit(1)

    module_name = _sanitize_identifier(name)
    module_content, snippet = _plugin_template(kind, module_name)
    out_dir = Path(output_dir)
    plugin_path = out_dir / f"{module_name}.py"
    test_path = Path("tests") / f"test_{module_name}_plugin.py"

    if plugin_path.exists():
        print(f"{plugin_path} already exists — refusing to overwrite.")
        sys.exit(1)
    if with_test and test_path.exists():
        print(f"{test_path} already exists — refusing to overwrite.")
        sys.exit(1)

    out_dir.mkdir(parents=True, exist_ok=True)
    plugin_path.write_text(module_content)
    print(f"Created {plugin_path}")

    if with_test:
        test_path.parent.mkdir(parents=True, exist_ok=True)
        test_path.write_text(
            "import importlib\n\n"
            f"def test_{module_name}_importable():\n"
            f"    mod = importlib.import_module('plugins.{module_name}')\n"
            f"    assert hasattr(mod, '{module_name}')\n"
        )
        print(f"Created {test_path}")

    print("\nTOML snippet:")
    print(snippet.rstrip())
    print(f"\nRun it with: {cli_name} retrain.toml")


def _run_plugins(args: list[str]) -> None:
    """List built-in and discovered plugins."""
    from retrain.advantages import (
        get_builtin_algorithm_modes,
        get_builtin_advantage_modes,
        get_builtin_transform_modes,
    )
    from retrain.config import TrainConfig, load_config
    from retrain.plugin_resolver import discover_plugin_modules, get_plugin_runtime
    from retrain.registry import get_registry

    fmt = "text"
    config_path: str | None = None
    for arg in args:
        if arg == "--json":
            fmt = "json"
        elif arg.startswith("--"):
            print(f"Unknown plugins flag: {arg}", file=sys.stderr)
            sys.exit(1)
        else:
            config_path = arg

    if config_path:
        cfg = load_config(config_path)
    else:
        cfg = TrainConfig()
    runtime = get_plugin_runtime()
    discovered = discover_plugin_modules(cfg.plugins_search_paths)

    import importlib

    discovered_entries: list[dict[str, str]] = []
    for module_name in discovered:
        try:
            importlib.import_module(module_name)
            status = "ok"
        except Exception as exc:
            status = f"error: {exc.__class__.__name__}"
        discovered_entries.append({"module": module_name, "status": status})

    builtins: dict[str, list[str]] = {
        "algorithm_mode": get_builtin_algorithm_modes(),
        "advantage_mode": get_builtin_advantage_modes(),
        "transform_mode": get_builtin_transform_modes(),
        "backend": get_registry("backend").builtin_names,
        "inference_engine": get_registry("inference_engine").builtin_names,
        "reward": get_registry("reward").builtin_names,
        "planning_detector": get_registry("planning_detector").builtin_names,
        "data_source": get_registry("data_source").builtin_names,
        "backpressure": get_registry("backpressure").builtin_names,
    }

    payload: dict[str, object] = {
        "runtime": {
            "search_paths": list(runtime.search_paths),
            "strict": runtime.strict,
        },
        "builtins": builtins,
        "discovered": discovered_entries,
    }

    if fmt == "json":
        print(json.dumps(payload, indent=2))
        return

    print("Plugin runtime:")
    print(f"  search_paths: {', '.join(runtime.search_paths)}")
    print(f"  strict      : {runtime.strict}")
    print("\nBuilt-ins:")
    for key, values in builtins.items():
        print(f"  {key}: {', '.join(values)}")
    print("\nDiscovered modules:")
    if discovered_entries:
        for item in discovered_entries:
            print(f"  {item['module']}: {item['status']}")
    else:
        print("  (none)")


def _load_dotenv() -> None:
    """Load .env file if present. Sets vars into os.environ."""
    env_path = Path(".env")
    if not env_path.exists():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        eq = line.find("=")
        if eq == -1:
            continue
        key = line[:eq].strip()
        val = line[eq + 1 :].strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
            val = val[1:-1]
        os.environ[key] = val
    print("Loaded .env", file=sys.stderr)


def _is_squeeze(path: str) -> bool:
    """Check if a TOML file has a [squeeze] section."""
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return "squeeze" in data


def _is_campaign(path: str) -> bool:
    """Check if a TOML file has a [campaign] section."""
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return "campaign" in data


def _resolve_backend_capability_payload(
    backend_name: str,
    backend_options: dict[str, object] | None = None,
) -> dict[str, object]:
    from retrain.backends.catalog import (
        backend_capability_source,
        resolve_backend_capabilities,
    )

    caps = resolve_backend_capabilities(backend_name, backend_options or {})
    return {
        "backend": backend_name,
        "source": backend_capability_source(backend_name, backend_options or {}),
        "reports_sync_loss": caps.reports_sync_loss,
        "preserves_token_advantages": caps.preserves_token_advantages,
        "supports_checkpoint_resume": caps.supports_checkpoint_resume,
        "resume_runtime_dependent": caps.resume_runtime_dependent,
        "supports_echo_shared_forward": caps.supports_echo_shared_forward,
    }


def _format_backend_capability_summary(capabilities: dict[str, object]) -> str:
    return (
        f"source={capabilities['source']}, "
        f"reports_sync_loss={capabilities['reports_sync_loss']}, "
        f"preserves_token_advantages={capabilities['preserves_token_advantages']}, "
        f"supports_checkpoint_resume={capabilities['supports_checkpoint_resume']}, "
        f"resume_runtime_dependent={capabilities['resume_runtime_dependent']}, "
        f"supports_echo_shared_forward={capabilities['supports_echo_shared_forward']}"
    )


def _run_backends(args: list[str]) -> None:
    """Print backend metadata catalog."""
    from retrain.backends.catalog import describe_backends_catalog

    fmt = "text"
    for arg in args:
        if arg == "--json":
            fmt = "json"
        elif arg.startswith("--"):
            print(f"Unknown backends flag: {arg}", file=sys.stderr)
            sys.exit(1)
        else:
            print(f"Unexpected argument for backends: {arg}", file=sys.stderr)
            sys.exit(1)

    payload = describe_backends_catalog()
    if fmt == "json":
        print(json.dumps(payload, indent=2))
        return

    print("Built-in backends:")
    for backend_item in _object_list(payload.get("builtins"), "backends.builtins"):
        name = str(backend_item.get("name", ""))
        dep = _object_dict(backend_item.get("dependency"), "backend.dependency")
        caps = _object_dict(backend_item.get("capabilities"), "backend.capabilities")
        print(f"  {name}")
        print(f"    dependency: {dep.get('import', '')} ({dep.get('hint', '')})")
        print(
            "    capabilities: "
            f"reports_sync_loss={caps.get('reports_sync_loss')}, "
            f"preserves_token_advantages={caps.get('preserves_token_advantages')}, "
            f"supports_checkpoint_resume={caps.get('supports_checkpoint_resume')}, "
            f"resume_runtime_dependent={caps.get('resume_runtime_dependent')}, "
            f"supports_echo_shared_forward={caps.get('supports_echo_shared_forward')}"
        )
        option_schema = _object_dict(
            backend_item.get("option_schema"),
            "backend.option_schema",
        )
        if option_schema:
            print("    options:")
            for key, raw_spec in sorted(option_schema.items()):
                spec = _object_dict(raw_spec, f"backend.option_schema.{key}")
                choices = spec.get("choices")
                choice_text = f" choices={choices}" if choices else ""
                print(
                    f"      {key}: type={spec.get('type')} "
                    f"default={spec.get('default')!r}{choice_text}"
                )
        else:
            print("    options: none")

    plugin = _object_dict(payload.get("plugin"), "backends.plugin")
    print("\nPlugin metadata hooks:")
    print(f"  dotted_path_supported: {plugin.get('dotted_path_supported')}")
    print(
        "  capability_hooks     : "
        f"{', '.join(_string_list(plugin.get('capability_hooks'), 'plugin.capability_hooks'))}"
    )
    print(
        "  option_schema_hooks  : "
        f"{', '.join(_string_list(plugin.get('option_schema_hooks'), 'plugin.option_schema_hooks'))}"
    )
    print(f"  schema_format        : {plugin.get('option_schema_format', '')}")


def _run_doctor() -> None:
    """Print dependency status for all known components."""
    from retrain.backends.catalog import get_builtin_backend_definitions
    from retrain.registry import check_environment, probe_backend_runtime

    print("retrain doctor — checking component dependencies\n")
    results = check_environment(config=None)
    all_ok = True
    for name, import_name, hint, available in results:
        status = "OK" if available else "MISSING"
        if not available:
            all_ok = False
        print(f"  {name:20s} {import_name:25s} {status}")
        if not available:
            print(f"  {'':20s} -> {hint}")

    print("\nBackend capability summary:")
    for backend_name in sorted(get_builtin_backend_definitions()):
        caps = _resolve_backend_capability_payload(backend_name, {})
        print(f"  {backend_name:20s} {_format_backend_capability_summary(caps)}")
    plugin_caps = _resolve_backend_capability_payload("myplugin.CustomBackend", {})
    print(f"  {'plugin/default':20s} {_format_backend_capability_summary(plugin_caps)}")

    print("\nRuntime probes:")
    for probe in probe_backend_runtime(config=None):
        print(
            f"  {probe.backend:20s} {probe.probe:20s} "
            f"{probe.status.upper():5s} {probe.detail}"
        )

    print()
    if all_ok:
        print("All optional dependencies are installed.")
    else:
        print("Some optional dependencies are missing (see above).")


def _check_environment(config: "TrainConfig") -> None:
    """Warn if the config references components whose deps are missing."""
    from retrain.registry import check_environment

    results = check_environment(config=config)
    for name, import_name, hint, available in results:
        if not available:
            print(
                f"WARNING: component '{name}' requires '{import_name}' "
                f"which is not installed.\n  -> {hint}"
            )


def _run_status(args: list[str]) -> None:
    """Scan log directories and print run/campaign status."""
    import time as _time

    from retrain.status import (
        format_campaign,
        format_run,
        format_summary_banner,
        scan_all,
    )

    fmt = "text"
    root = "logs"
    show_all = False
    watch = False
    positional: list[str] = []
    for arg in args:
        if arg == "--json":
            fmt = "json"
        elif arg == "--all":
            show_all = True
        elif arg == "--active":
            show_all = False
        elif arg == "--watch":
            watch = True
        elif arg.startswith("--"):
            print(f"Unknown status flag: {arg}", file=sys.stderr)
            sys.exit(1)
        else:
            positional.append(arg)

    if positional:
        root = positional[0]

    root_path = Path(root)
    if not root_path.is_dir():
        print(f"No log directory found: {root}")
        sys.exit(1)

    _stale_hide_seconds = 86400  # hide dead/stale-partial campaigns after 24h

    while True:
        now = _time.time()
        runs, campaigns = scan_all(root_path)

        # Banner uses ALL campaigns (before filtering)
        banner = format_summary_banner(campaigns)

        if not show_all:

            from retrain.status import CampaignSummary

            def _is_visible(c: CampaignSummary) -> bool:
                if c.status == "running":
                    return True
                if c.status in ("dead", "partial", "done"):
                    # Show only if there was recent activity
                    return c.last_activity > now - _stale_hide_seconds
                return True

            campaigns = [c for c in campaigns if _is_visible(c)]

        if fmt == "json":
            payload = {
                "root": str(root_path),
                "runs": [r.to_dict() for r in runs],
                "campaigns": [c.to_dict() for c in campaigns],
            }
            print(json.dumps(payload, indent=2))
            if not watch:
                return
        else:
            print(banner)
            print()
            if not runs and not campaigns:
                if show_all:
                    print(f"No runs or campaigns found in {root}")
                else:
                    print(f"No active campaigns in {root}  (use --all to see everything)")
            else:
                if campaigns:
                    for camp in campaigns:
                        print(format_campaign(camp))
                        print()

                if runs:
                    print("Standalone runs:")
                    for run in runs:
                        print(format_run(run))

        if not watch:
            return

        try:
            _time.sleep(5)
            # Clear screen for refresh
            print("\033[2J\033[H", end="")
        except KeyboardInterrupt:
            return


def _run_top(args: list[str]) -> None:
    """Live dashboard: alias for ``retrain status --watch --active``."""
    status_args = ["--watch", "--active"]
    # Accept optional positional logdir
    for arg in args:
        if not arg.startswith("-"):
            status_args.append(arg)
            break
    _run_status(status_args)


def _explain_single(config_path: str | None, fmt: str) -> None:
    """Explain what a single training run would do."""
    import warnings

    from retrain.config import load_config
    from retrain.registry import check_environment

    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        config = load_config(config_path)

    if config.trainer == "sft":
        condition = "sft"
        datums_per_step = config.sft_batch_size if config.sft_batch_size > 0 else config.batch_size
    else:
        condition = (
            config.algorithm_mode
            if config.algorithm_mode
            else f"{config.advantage_mode}+{config.transform_mode}"
        )
        datums_per_step = config.batch_size * config.group_size
    total_datums = datums_per_step * config.max_steps
    sft_loss_fn = config.sft_loss_fn
    if sft_loss_fn == "auto":
        sft_loss_fn = "cross_entropy" if config.trainer == "sft" else "importance_sampling"
    lora_alpha = config.lora_alpha if config.lora_alpha else config.lora_rank * 2
    data_info = config.data_source
    if config.environment_provider:
        data_info = f"{config.environment_provider}:{config.environment_id}"
    if config.trainer == "sft":
        data_info = config.sft_data_path
    backend_capabilities = _resolve_backend_capability_payload(
        config.backend,
        config.backend_options,
    )

    info: dict = {
        "mode": "single",
        "config": config_path or "retrain.toml",
        "model": config.model,
        "trainer": config.trainer,
        "backend": config.backend,
        "backend_options": dict(config.backend_options),
        "backend_capabilities": backend_capabilities,
        "condition": condition,
        "algorithm_mode": config.algorithm_mode,
        "advantage_mode": config.advantage_mode,
        "transform_mode": config.transform_mode,
        "max_steps": config.max_steps,
        "batch_size": config.batch_size,
        "group_size": config.group_size,
        "datums_per_step": datums_per_step,
        "total_datums": total_datums,
        "sft_warmup_steps": config.sft_warmup_steps,
        "sft_data_path": config.sft_data_path,
        "sft_batch_size": config.sft_batch_size,
        "sft_max_tokens": config.sft_max_tokens,
        "sft_loss_fn": sft_loss_fn,
        "sft_batch_order": config.sft_batch_order,
        "sft_length_bucket_size": config.sft_length_bucket_size,
        "max_tokens": config.max_tokens,
        "temperature": config.temperature,
        "lr": config.lr,
        "seed": config.seed,
        "lora_rank": config.lora_rank,
        "lora_alpha": lora_alpha,
        "data": data_info,
        "reward_type": config.reward_type,
        "log_dir": config.log_dir,
        "adapter_path": config.adapter_path,
        "wandb_project": config.wandb_project or "(disabled)",
        "warnings": [str(w.message) for w in caught],
    }

    # Dependency warnings
    dep_warnings = []
    results = check_environment(config=config)
    for name, import_name, hint, available in results:
        if not available:
            dep_warnings.append(f"{name} requires {import_name} ({hint})")
    if dep_warnings:
        info["dep_warnings"] = dep_warnings

    if fmt == "json":
        print(json.dumps(info, indent=2))
        return

    print(f"retrain explain — dry-run preview")
    print(f"  config        : {info['config']}")
    print(f"  model         : {config.model}")
    print(f"  trainer       : {config.trainer}")
    print(f"  backend       : {config.backend}")
    print(f"  backend caps  : {_format_backend_capability_summary(backend_capabilities)}")
    if not backend_capabilities["reports_sync_loss"]:
        print("  note          : loss is reported as placeholder by backend design")
    print(f"  condition     : {condition}")
    print(f"  steps         : {config.max_steps}")
    print(f"  batch_size    : {config.batch_size}")
    if config.trainer == "sft":
        print(f"  sft_batch     : {datums_per_step}")
    else:
        print(f"  group_size    : {config.group_size}")
    print(f"  datums/step   : {datums_per_step}")
    print(f"  total datums  : {total_datums}")
    print(f"  max_tokens    : {config.max_tokens}")
    print(f"  temperature   : {config.temperature}")
    print(f"  lr            : {config.lr}")
    if config.trainer == "sft" or config.sft_warmup_steps > 0:
        print(
            "  sft           : "
            f"steps={config.max_steps if config.trainer == 'sft' else config.sft_warmup_steps} "
            f"batch={config.sft_batch_size or '(default)'} "
            f"loss={sft_loss_fn} "
            f"order={config.sft_batch_order}"
        )
        if config.sft_data_path:
            print(f"  sft_data      : {config.sft_data_path}")
    print(f"  seed          : {config.seed}")
    print(f"  lora          : rank={config.lora_rank} alpha={lora_alpha}")
    print(f"  data          : {data_info}")
    print(f"  reward        : {config.reward_type}")
    print(f"  log_dir       : {config.log_dir}")
    print(f"  adapter_path  : {config.adapter_path}")
    print(f"  wandb         : {info['wandb_project']}")
    if caught:
        print("\nWarnings:")
        for w in caught:
            print(f"  - {w.message}")
    if dep_warnings:
        print("\nMissing dependencies:")
        for dw in dep_warnings:
            print(f"  - {dw}")


def _explain_campaign(config_path: str, fmt: str) -> None:
    """Explain what a campaign would do."""
    from retrain.campaign import DEFAULT_SEEDS, _parse_campaign_conditions

    with open(config_path, "rb") as f:
        data = tomllib.load(f)

    campaign = data.get("campaign", {})
    seeds = campaign.get("seeds", DEFAULT_SEEDS)
    max_steps = campaign.get("max_steps", 500)
    raw_conditions = campaign.get("conditions", None)
    conditions = _parse_campaign_conditions(raw_conditions, config_path)
    condition_labels = [c.label for c in conditions]
    total_runs = len(conditions) * len(seeds)
    backend_sec = data.get("backend", {})
    backend_name = "local"
    backend_options: dict[str, object] = {}
    if isinstance(backend_sec, dict):
        backend_name = str(backend_sec.get("backend", "local") or "local")
        raw_options = backend_sec.get("options", {})
        if isinstance(raw_options, dict):
            backend_options = dict(raw_options)
    backend_capabilities = _resolve_backend_capability_payload(
        backend_name,
        backend_options,
    )

    info = {
        "mode": "campaign",
        "config": config_path,
        "backend": backend_name,
        "backend_capabilities": backend_capabilities,
        "conditions": condition_labels,
        "seeds": seeds,
        "max_steps": max_steps,
        "total_runs": total_runs,
    }

    if fmt == "json":
        print(json.dumps(info, indent=2))
        return

    print(f"retrain explain — campaign dry-run preview")
    print(f"  config        : {config_path}")
    print(f"  backend       : {backend_name}")
    print(f"  backend caps  : {_format_backend_capability_summary(backend_capabilities)}")
    print(f"  conditions    : {', '.join(condition_labels)}")
    print(f"  seeds         : {seeds}")
    print(f"  max_steps     : {max_steps}")
    print(f"  total runs    : {total_runs}")


def _explain_squeeze(config_path: str, fmt: str) -> None:
    """Explain what a squeeze run would do."""
    from retrain.config import load_squeeze_config

    cfg = load_squeeze_config(config_path)

    info = {
        "mode": "squeeze",
        "config": config_path,
        "adapter_path": cfg.adapter_path,
        "source_rank": cfg.source_rank,
        "min_variance_retention": cfg.min_variance_retention,
    }
    if cfg.output_path:
        info["output_path"] = cfg.output_path
    if cfg.compress_to > 0:
        info["compress_to"] = cfg.compress_to

    if fmt == "json":
        print(json.dumps(info, indent=2))
        return

    print(f"retrain explain — squeeze dry-run preview")
    print(f"  config                : {config_path}")
    print(f"  adapter_path          : {cfg.adapter_path}")
    print(f"  source_rank           : {cfg.source_rank}")
    print(f"  min_variance_retention: {cfg.min_variance_retention}")
    if cfg.output_path:
        print(f"  output_path           : {cfg.output_path}")
    if cfg.compress_to > 0:
        print(f"  compress_to           : {cfg.compress_to}")


def _run_diff(args: list[str]) -> None:
    """Compare two runs or campaign conditions."""
    from retrain.diff import diff_conditions, diff_runs, format_diff

    fmt = "text"
    positional: list[str] = []
    for arg in args:
        if arg == "--json":
            fmt = "json"
        elif arg.startswith("--"):
            print(f"Unknown diff flag: {arg}", file=sys.stderr)
            sys.exit(1)
        else:
            positional.append(arg)

    if len(positional) == 2:
        dir_a, dir_b = Path(positional[0]), Path(positional[1])
        try:
            result = diff_runs(dir_a, dir_b)
        except FileNotFoundError as exc:
            print(str(exc), file=sys.stderr)
            sys.exit(1)
    elif len(positional) == 3:
        campaign_dir = Path(positional[0])
        cond_a, cond_b = positional[1], positional[2]
        try:
            result = diff_conditions(campaign_dir, cond_a, cond_b)
        except FileNotFoundError as exc:
            print(str(exc), file=sys.stderr)
            sys.exit(1)
    else:
        print("Usage:", file=sys.stderr)
        print("  retrain diff <run_a> <run_b>", file=sys.stderr)
        print("  retrain diff <campaign_dir> <cond_a> <cond_b>", file=sys.stderr)
        sys.exit(1)

    if fmt == "json":
        print(json.dumps(result.to_dict(), indent=2))
    else:
        print(format_diff(result))


def _run_benchmark(args: list[str]) -> None:
    """Run or summarize a benchmark suite."""
    from retrain.benchmark import (
        default_benchmark_output_dir,
        format_run_summary,
        format_suite_summary,
        run_benchmark_suite,
        summarize_run,
        summarize_suite,
    )
    from retrain.config import load_config, parse_cli_overrides
    from retrain.registry import get_registry

    fmt = "text"
    repeats = 1
    output_dir: str | None = None
    passthrough: list[str] = []

    i = 0
    while i < len(args):
        arg = args[i]
        if arg == "--json":
            fmt = "json"
        elif arg.startswith("--repeat="):
            repeats = int(arg.split("=", 1)[1])
        elif arg == "--repeat":
            i += 1
            if i >= len(args):
                print("Flag --repeat requires a value.", file=sys.stderr)
                sys.exit(1)
            repeats = int(args[i])
        elif arg.startswith("--output-dir="):
            output_dir = arg.split("=", 1)[1]
        elif arg == "--output-dir":
            i += 1
            if i >= len(args):
                print("Flag --output-dir requires a value.", file=sys.stderr)
                sys.exit(1)
            output_dir = args[i]
        else:
            passthrough.append(arg)
        i += 1

    config_path, overrides = parse_cli_overrides(passthrough)
    if config_path is None:
        print("Usage:", file=sys.stderr)
        print(
            "  retrain benchmark <config.toml> [--repeat N] [--output-dir DIR] [--json]",
            file=sys.stderr,
        )
        print(
            "  retrain benchmark <run_dir|suite_dir> [--json]",
            file=sys.stderr,
        )
        sys.exit(1)

    target = Path(config_path)
    if target.is_dir():
        try:
            if (target / "metrics.jsonl").is_file():
                run_summary = summarize_run(target)
                if fmt == "json":
                    print(json.dumps(run_summary.to_dict(), indent=2))
                else:
                    print(format_run_summary(run_summary))
                return
            suite_summary = summarize_suite(target)
        except FileNotFoundError as exc:
            print(str(exc), file=sys.stderr)
            sys.exit(1)
        if fmt == "json":
            print(json.dumps(suite_summary.to_dict(), indent=2))
        else:
            print(format_suite_summary(suite_summary))
        return

    if not target.is_file():
        print(f"File not found: {target}", file=sys.stderr)
        sys.exit(1)

    config = load_config(str(target), overrides=overrides)
    _check_environment(config)
    suite_dir = Path(output_dir) if output_dir else default_benchmark_output_dir(
        str(target),
        config,
    )
    suite_summary = run_benchmark_suite(
        config,
        repeats=repeats,
        output_dir=suite_dir,
        runner_factory=lambda cfg: get_registry("trainer").create(cfg.trainer, cfg),
        disable_wandb=True,
    )
    if fmt == "json":
        print(json.dumps(suite_summary.to_dict(), indent=2))
    else:
        print(format_suite_summary(suite_summary))


def _run_migrate_config(args: list[str]) -> None:
    """Migrate legacy backend config keys to [backend.options] format."""
    from retrain.config import migrate_legacy_backend_keys_toml_text

    check_only = False
    write_in_place = False
    backup = False
    stdin_mode = False
    stdout_mode = False
    json_mode = False
    output_path: str | None = None
    positional: list[str] = []

    i = 0
    while i < len(args):
        arg = args[i]
        if arg == "--check":
            check_only = True
        elif arg == "--write":
            write_in_place = True
        elif arg == "--backup":
            backup = True
        elif arg == "--stdin":
            stdin_mode = True
        elif arg == "--stdout":
            stdout_mode = True
        elif arg == "--json":
            json_mode = True
        elif arg in ("--output", "-o"):
            i += 1
            if i >= len(args):
                print("Flag --output requires a path.", file=sys.stderr)
                sys.exit(1)
            output_path = args[i]
        elif arg.startswith("--output="):
            output_path = arg.split("=", 1)[1]
        elif arg.startswith("--"):
            print(f"Unknown migrate-config flag: {arg}", file=sys.stderr)
            sys.exit(1)
        else:
            positional.append(arg)
        i += 1

    if stdin_mode and positional:
        print("Use either a config path or --stdin, not both.", file=sys.stderr)
        sys.exit(1)
    if not stdin_mode and len(positional) != 1:
        print(
            "Usage: retrain migrate-config <config.toml> "
            "[--check|--write|--output PATH] [--backup] [--stdin|--stdout] [--json]",
            file=sys.stderr,
        )
        sys.exit(1)
    if check_only and (write_in_place or output_path or stdout_mode or backup):
        print(
            "Flag --check cannot be combined with --write, --output, --stdout, or --backup.",
            file=sys.stderr,
        )
        sys.exit(1)
    if stdin_mode and write_in_place:
        print("Flag --write requires a file path input (cannot be used with --stdin).", file=sys.stderr)
        sys.exit(1)
    if write_in_place and output_path:
        print("Use either --write or --output, not both.", file=sys.stderr)
        sys.exit(1)
    if stdout_mode and (write_in_place or output_path):
        print("Flag --stdout cannot be combined with --write or --output.", file=sys.stderr)
        sys.exit(1)
    if backup and not write_in_place:
        print("Flag --backup can only be used with --write.", file=sys.stderr)
        sys.exit(1)

    config_path: Path | None = None
    source_label = "<stdin>"
    if stdin_mode:
        original_text = sys.stdin.read()
        if not original_text:
            print("No TOML content received on stdin.", file=sys.stderr)
            sys.exit(1)
    else:
        config_path = Path(positional[0])
        if not config_path.is_file():
            print(f"File not found: {config_path}", file=sys.stderr)
            sys.exit(1)
        source_label = str(config_path)
        original_text = config_path.read_text()

    try:
        migrated = migrate_legacy_backend_keys_toml_text(original_text)
    except tomllib.TOMLDecodeError as exc:
        print(f"Invalid TOML in {source_label}: {exc}", file=sys.stderr)
        sys.exit(1)

    needs_migration = bool(migrated.legacy_keys)
    diff_text = "\n".join(
        difflib.unified_diff(
            original_text.splitlines(),
            migrated.output_text.splitlines(),
            fromfile=source_label,
            tofile=f"{source_label}.migrated",
            lineterm="",
        )
    )

    mode = "preview"
    if check_only:
        mode = "check"
    elif write_in_place:
        mode = "write"
    elif output_path:
        mode = "output"
    elif stdout_mode:
        mode = "stdout"

    payload: dict[str, object] = {
        "config": source_label,
        "mode": mode,
        "needs_migration": needs_migration,
        "changed": migrated.changed,
        "legacy_keys": list(migrated.legacy_keys),
        "merged_backend_options": migrated.merged_backend_options,
        "diff": diff_text,
        "written": False,
        "output_path": None,
        "backup_path": None,
    }

    if check_only:
        if json_mode:
            print(json.dumps(payload, indent=2))
        elif needs_migration:
            keys = ", ".join(migrated.legacy_keys)
            print(f"Migration required in {source_label} (legacy keys: {keys}).")
        else:
            print(f"No migration needed: {source_label}")
        if needs_migration:
            sys.exit(1)
        return

    if write_in_place:
        assert config_path is not None
        if backup:
            backup_path = Path(str(config_path) + ".bak")
            backup_path.write_text(original_text)
            payload["backup_path"] = str(backup_path)
        config_path.write_text(migrated.output_text)
        payload["written"] = True
        payload["output_path"] = str(config_path)
    elif output_path:
        out_path = Path(output_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(migrated.output_text)
        payload["written"] = True
        payload["output_path"] = str(out_path)

    if json_mode:
        print(json.dumps(payload, indent=2))
        return

    if stdout_mode:
        print(migrated.output_text, end="")
        return

    if payload["written"]:
        if needs_migration:
            print(f"Migrated config written to {payload['output_path']}")
        else:
            print(f"No migration required. Wrote unchanged config to {payload['output_path']}")
        if payload["backup_path"]:
            print(f"Backup written to {payload['backup_path']}")
        return

    if needs_migration:
        print(diff_text)
    else:
        print(f"No migration needed: {source_label}")


def _run_explain(args: list[str]) -> None:
    """Dry-run: show what a config would do without running it."""
    fmt = "text"
    config_path: str | None = None
    for arg in args:
        if arg == "--json":
            fmt = "json"
        elif arg.startswith("--"):
            print(f"Unknown explain flag: {arg}", file=sys.stderr)
            sys.exit(1)
        else:
            config_path = arg

    # Resolve config path
    if config_path is None:
        if Path("retrain.toml").is_file():
            config_path = "retrain.toml"
        else:
            print("No config file specified and no retrain.toml in cwd.")
            sys.exit(1)

    if not Path(config_path).is_file():
        print(f"File not found: {config_path}")
        sys.exit(1)

    # Route by config type
    if _is_campaign(config_path):
        _explain_campaign(config_path, fmt)
    elif _is_squeeze(config_path):
        _explain_squeeze(config_path, fmt)
    else:
        _explain_single(config_path, fmt)


def _run_trace(args: list[str]) -> None:
    """Pre-flight validation: build flow, trace with synthetic data."""
    from retrain.config import load_config
    from retrain.flow import build_flow

    config_path: str | None = None
    json_mode = False
    for arg in args:
        if arg == "--json":
            json_mode = True
        elif not arg.startswith("--") and config_path is None:
            config_path = arg
        else:
            print(f"Unknown argument: {arg}", file=sys.stderr)
            sys.exit(1)

    if config_path is not None and not Path(config_path).is_file():
        print(f"File not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    try:
        config = load_config(config_path)
    except (ValueError, FileNotFoundError) as exc:
        print(f"Config error: {exc}", file=sys.stderr)
        sys.exit(1)

    flow = build_flow(config, gpu=False)
    result = flow.trace()

    if json_mode:
        payload = {
            "ok": result.ok,
            "probe_cases_run": result.probe_cases_run,
            "probe_cases_passed": result.probe_cases_passed,
            "issues": [
                {
                    "severity": i.severity,
                    "category": i.category,
                    "message": i.message,
                }
                for i in result.issues
            ],
            "flow": {
                "condition_label": flow.condition_label,
                "backend": config.backend,
                "backend_capability_source": flow.backend_capability_source,
                "needs_planning": flow.needs_planning,
                "uses_sepa_controller": flow.uses_sepa_controller,
                "preserves_token_advantages": flow.backend_capabilities.preserves_token_advantages,
            },
        }
        print(json.dumps(payload, indent=2))
    else:
        print(f"Condition: {flow.condition_label}")
        print(f"Backend:   {config.backend} (source: {flow.backend_capability_source})")
        print(
            f"Probes:    {result.probe_cases_passed}/{result.probe_cases_run} passed"
        )
        if result.issues:
            print()
            for issue in result.issues:
                tag = "[ERROR]" if issue.severity == "error" else "[WARN]"
                print(f"  {tag} [{issue.category}] {issue.message}")
        print()
        if result.ok:
            print("PASS")
        else:
            print("FAIL")

    sys.exit(0 if result.ok else 1)


def _run_tree(args: list[str]) -> None:
    """Experiment tech-tree commands."""
    from retrain.tree import (
        format_next,
        format_show,
        format_tree,
        format_tree_json,
        load_tree,
        reset_node,
    )

    usage = (
        "Usage:\n"
        "  retrain tree [tree.toml] [--json]          — view tree\n"
        "  retrain tree next [tree.toml]              — show pending nodes\n"
        "  retrain tree show <node> [tree.toml] [--json] — node details\n"
        "  retrain tree run <node> [tree.toml]        — launch node's campaign\n"
        '  retrain tree note <node> "text" [tree.toml] — add annotation\n'
        "  retrain tree eval [tree.toml]              — evaluate success conditions\n"
        "  retrain tree reset <node> [tree.toml]      — reset node to pending\n"
    )

    if not args or args[0] in ("-h", "--help"):
        print(usage)
        return

    # Extract --json flag
    json_flag = "--json" in args
    if json_flag:
        args = [a for a in args if a != "--json"]

    # Determine subcommand vs bare tree path
    subcommands = {"next", "run", "note", "eval", "show", "reset"}
    if args and args[0] in subcommands:
        subcmd = args[0]
        rest = args[1:]
    else:
        # Default: view
        subcmd = "view"
        rest = args

    # --- view ---
    if subcmd == "view":
        tree_path = rest[0] if rest else "tree.toml"
        tree = load_tree(tree_path)
        if json_flag:
            print(json.dumps(format_tree_json(tree), indent=2))
        else:
            print(format_tree(tree))
        return

    # --- next ---
    if subcmd == "next":
        tree_path = rest[0] if rest else "tree.toml"
        tree = load_tree(tree_path)
        print(format_next(tree))
        return

    # --- show <node> [tree.toml] ---
    if subcmd == "show":
        if not rest:
            print("Error: 'show' requires a node id.")
            print(usage)
            sys.exit(1)
        node_id = rest[0]
        tree_path = rest[1] if len(rest) > 1 else "tree.toml"
        tree = load_tree(tree_path)
        try:
            if json_flag:
                data = format_tree_json(tree)
                node_data = [n for n in data["nodes"] if n["id"] == node_id]
                if not node_data:
                    raise KeyError(node_id)
                print(json.dumps(node_data[0], indent=2))
            else:
                print(format_show(tree, node_id))
        except KeyError:
            print(f"Error: unknown node {node_id!r}")
            sys.exit(1)
        return

    # --- run <node> [tree.toml] ---
    if subcmd == "run":
        if not rest:
            print("Error: 'run' requires a node id.")
            print(usage)
            sys.exit(1)
        node_id = rest[0]
        tree_path = rest[1] if len(rest) > 1 else "tree.toml"
        tree = load_tree(tree_path)
        _tree_run_node(tree, node_id)
        return

    # --- note <node> "text" [tree.toml] ---
    if subcmd == "note":
        if len(rest) < 2:
            print("Error: 'note' requires a node id and text.")
            print(usage)
            sys.exit(1)
        node_id = rest[0]
        text = rest[1]
        tree_path = rest[2] if len(rest) > 2 else "tree.toml"
        tree = load_tree(tree_path)
        _tree_add_note(tree, node_id, text)
        return

    # --- eval [tree.toml] ---
    if subcmd == "eval":
        tree_path = rest[0] if rest else "tree.toml"
        tree = load_tree(tree_path)
        _tree_eval(tree)
        return

    # --- reset <node> [tree.toml] ---
    if subcmd == "reset":
        if not rest:
            print("Error: 'reset' requires a node id.")
            print(usage)
            sys.exit(1)
        node_id = rest[0]
        tree_path = rest[1] if len(rest) > 1 else "tree.toml"
        tree = load_tree(tree_path)
        reset_node(tree, node_id)
        print(f"Node {node_id!r} reset to pending.")
        return

    print(f"Unknown tree subcommand: {subcmd}")
    print(usage)
    sys.exit(1)


def _tree_run_node(tree, node_id: str) -> None:
    """Launch a node's campaign and record state."""
    from datetime import datetime, timezone

    from retrain.campaign import run_campaign
    from retrain.tree import save_state

    if node_id not in tree.node_map:
        print(f"Error: unknown node {node_id!r}")
        sys.exit(1)

    node = tree.node_map[node_id]
    from retrain.tree import NodeState

    ns = tree.state.nodes.setdefault(node_id, NodeState())

    ns.status = "running"
    ns.started_at = datetime.now(timezone.utc).isoformat()
    save_state(tree)

    print(f"Running node {node_id!r}: {node.campaign}")
    campaign_dir = run_campaign(node.campaign)

    ns.campaign_dir = campaign_dir
    ns.status = "done"
    ns.completed_at = datetime.now(timezone.utc).isoformat()
    save_state(tree)

    print(f"Node {node_id!r} campaign completed. Dir: {campaign_dir}")
    print("Run 'retrain tree eval' to evaluate success conditions.")


def _tree_add_note(tree, node_id: str, text: str) -> None:
    """Add an annotation to a node."""
    from datetime import datetime, timezone

    from retrain.tree import Annotation, NodeState, save_state

    if node_id not in tree.node_map:
        print(f"Error: unknown node {node_id!r}")
        sys.exit(1)

    ns = tree.state.nodes.setdefault(node_id, NodeState())
    ns.annotations.append(
        Annotation(text=text, at=datetime.now(timezone.utc).isoformat())
    )
    save_state(tree)
    print(f"Note added to {node_id!r}.")


def _tree_eval(tree) -> None:
    """Evaluate success conditions for all done nodes without outcomes."""
    from retrain.tree import evaluate_node

    evaluated = 0
    for node in tree.nodes:
        ns = tree.state.nodes.get(node.id)
        if ns and ns.status == "done" and not ns.outcome:
            if node.success_condition is None:
                print(f"  {node.id}: no success condition defined")
                continue
            try:
                outcome = evaluate_node(tree, node.id)
                result_str = ""
                if ns.result:
                    parts = [f"{k}={v}" for k, v in ns.result.items()]
                    result_str = f" ({', '.join(parts)})"
                print(f"  {node.id}: {outcome}{result_str}")
                evaluated += 1
            except Exception as e:
                print(f"  {node.id}: error — {e}")

    if evaluated == 0:
        print("No nodes to evaluate.")


def main() -> None:
    """Single entry point: retrain config.toml"""
    _load_dotenv()

    args = sys.argv[1:]
    cli_name = resolve_cli_name()

    if args and args[0] in ("-h", "--help", "help"):
        print_help(cli_name)
        sys.exit(0)

    if args and args[0] in ("man", "manual"):
        manual_command.run(args[1:], cli_name=cli_name, manual_path=_manual_path)
        sys.exit(0)

    if args and args[0] == "backends":
        _run_backends(args[1:])
        sys.exit(0)

    if args and args[0] == "doctor":
        _run_doctor()
        sys.exit(0)

    if args and args[0] == "migrate-config":
        _run_migrate_config(args[1:])
        sys.exit(0)

    if args and args[0] == "init":
        _run_init(args=args[1:], cli_name=cli_name)
        sys.exit(0)

    if args and args[0] == "init-plugin":
        _run_init_plugin(args=args[1:], cli_name=cli_name)
        sys.exit(0)

    if args and args[0] == "plugins":
        _run_plugins(args[1:])
        sys.exit(0)

    if args and args[0] == "status":
        _run_status(args[1:])
        sys.exit(0)

    if args and args[0] == "top":
        _run_top(args[1:])
        sys.exit(0)

    if args and args[0] == "explain":
        _run_explain(args[1:])
        sys.exit(0)

    if args and args[0] == "diff":
        _run_diff(args[1:])
        sys.exit(0)

    if args and args[0] == "benchmark":
        _run_benchmark(args[1:])
        sys.exit(0)

    if args and args[0] == "trace":
        _run_trace(args[1:])
        sys.exit(0)

    if args and args[0] == "tree":
        _run_tree(args[1:])
        sys.exit(0)

    # Parse CLI overrides
    from retrain.config import parse_cli_overrides

    config_path, overrides = parse_cli_overrides(args)

    # Resolve config path
    if config_path is None:
        if Path("retrain.toml").is_file():
            config_path = "retrain.toml"
        elif not overrides:
            if sys.stdin.isatty():
                answer = input("No retrain.toml found. Create one now? [Y/n]: ").strip().lower()
                if answer in ("", "y", "yes"):
                    _run_init(cli_name=cli_name)
                    sys.exit(0)
            print("No retrain.toml found. Create one with:")
            print(f"  {cli_name} init")
            print("Or pass a path:")
            print(f"  {cli_name} path/to/config.toml")
            print("Manual:")
            print(f"  {cli_name} man")
            sys.exit(1)
        # else: overrides-only mode, use defaults

    if config_path is not None and not Path(config_path).is_file():
        print(f"File not found: {config_path}")
        sys.exit(1)

    # Route: campaign | squeeze | single run
    # Campaign/squeeze only when a TOML file is provided (CLI overrides don't apply)
    if config_path is not None and _is_campaign(config_path):
        from retrain.campaign import run_campaign
        run_campaign(config_path)
    elif config_path is not None and _is_squeeze(config_path):
        from retrain.squeeze import run_squeeze
        run_squeeze(config_path)
    else:
        from retrain.config import load_config
        from retrain.registry import get_registry
        config = load_config(config_path, overrides=overrides)
        _check_environment(config)
        meta_dir = Path(config.log_dir)
        meta_dir.mkdir(parents=True, exist_ok=True)
        meta_path = meta_dir / "run_meta.json"
        meta_path.write_text(
            json.dumps(
                {
                    "trainer": config.trainer,
                    "run_id": meta_dir.name or "run",
                    "status": "running",
                }
            )
        )
        runner = get_registry("trainer").create(config.trainer, config)
        result = runner.run(config)
        meta: dict[str, object] = {"trainer": config.trainer}
        meta.update(result.to_dict())
        meta_path.write_text(json.dumps(meta))
        if not result.ok:
            print(
                f"Training failed ({result.failure_status}): {result.error_message}",
                file=sys.stderr,
            )
            sys.exit(1)


if __name__ == "__main__":
    main()
