"""Single entry point for retrain.

Usage:
    retrain                  # loads retrain.toml from cwd
    retrain config.toml      # single training run
    retrain campaign.toml    # campaign (if TOML has [campaign] section)
    retrain init             # generate a starter retrain.toml
    retrain doctor           # check installed dependencies for all components
    retrain --seed 42 --lr 1e-4   # override config values from CLI

A TOML with a [campaign] section runs multiple conditions × seeds.
A TOML without it runs a single training job. Same command either way.
"""

from __future__ import annotations

import os
import sys
import tomllib
from pathlib import Path


_STARTER_TOML = """\
# retrain configuration — generated by `retrain init`
# Docs: docs/configuration.md

[model]
model = "Qwen/Qwen3-4B-Instruct-2507"
lora_rank = 32

[algorithm]
advantage_mode = "maxrl"     # grpo | maxrl
transform_mode = "gtpo_sepa" # none | gtpo | gtpo_hicra | gtpo_sepa

[training]
seed = -1                    # -1 = no seed
max_steps = 100              # conservative default for first run
batch_size = 4               # conservative default for first run
group_size = 16
max_tokens = 2048
temperature = 0.7
lr = 4e-5
save_every = 20

[backend]
backend = "local"
adapter_path = "adapters/my_run"

[logging]
log_dir = "logs/train"
# wandb_project = ""         # uncomment to enable wandb
"""


def _run_init() -> None:
    """Generate a starter retrain.toml in the current directory."""
    dest = Path("retrain.toml")
    if dest.exists():
        print(f"retrain.toml already exists — refusing to overwrite.")
        sys.exit(1)
    dest.write_text(_STARTER_TOML)
    print(f"Created retrain.toml with conservative defaults.")
    print("Edit it, then run: retrain")


def _load_dotenv() -> None:
    """Load .env file if present. Sets vars into os.environ."""
    env_path = Path(".env")
    if not env_path.exists():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        eq = line.find("=")
        if eq == -1:
            continue
        key = line[:eq].strip()
        val = line[eq + 1 :].strip()
        if len(val) >= 2 and val[0] == val[-1] and val[0] in ('"', "'"):
            val = val[1:-1]
        os.environ[key] = val
    print("Loaded .env")


def _is_squeeze(path: str) -> bool:
    """Check if a TOML file has a [squeeze] section."""
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return "squeeze" in data


def _is_campaign(path: str) -> bool:
    """Check if a TOML file has a [campaign] section."""
    with open(path, "rb") as f:
        data = tomllib.load(f)
    return "campaign" in data


def _run_doctor() -> None:
    """Print dependency status for all known components."""
    from retrain.registry import check_environment

    print("retrain doctor — checking component dependencies\n")
    results = check_environment(config=None)
    all_ok = True
    for name, import_name, hint, available in results:
        status = "OK" if available else "MISSING"
        if not available:
            all_ok = False
        print(f"  {name:20s} {import_name:25s} {status}")
        if not available:
            print(f"  {'':20s} -> {hint}")
    print()
    if all_ok:
        print("All optional dependencies are installed.")
    else:
        print("Some optional dependencies are missing (see above).")


def _check_environment(config: "TrainConfig") -> None:  # noqa: F821
    """Warn if the config references components whose deps are missing."""
    from retrain.registry import check_environment

    results = check_environment(config=config)
    for name, import_name, hint, available in results:
        if not available:
            print(
                f"WARNING: component '{name}' requires '{import_name}' "
                f"which is not installed.\n  -> {hint}"
            )


def main() -> None:
    """Single entry point: retrain config.toml"""
    _load_dotenv()

    args = sys.argv[1:]

    if args and args[0] in ("-h", "--help", "help"):
        print(__doc__)
        sys.exit(0)

    if args and args[0] == "doctor":
        _run_doctor()
        sys.exit(0)

    if args and args[0] == "init":
        _run_init()
        sys.exit(0)

    # Parse CLI overrides
    from retrain.config import parse_cli_overrides

    config_path, overrides = parse_cli_overrides(args)

    # Resolve config path
    if config_path is None:
        if Path("retrain.toml").is_file():
            config_path = "retrain.toml"
        elif not overrides:
            print("No retrain.toml found. Create one with:")
            print("  retrain init")
            print("Or pass a path:")
            print("  retrain path/to/config.toml")
            sys.exit(1)
        # else: overrides-only mode, use defaults

    if config_path is not None and not Path(config_path).is_file():
        print(f"File not found: {config_path}")
        sys.exit(1)

    # Route: campaign | squeeze | single run
    # Campaign/squeeze only when a TOML file is provided (CLI overrides don't apply)
    if config_path is not None and _is_campaign(config_path):
        from retrain.campaign import run_campaign
        run_campaign(config_path)
    elif config_path is not None and _is_squeeze(config_path):
        from retrain.squeeze import run_squeeze
        run_squeeze(config_path)
    else:
        from retrain.config import load_config
        from retrain.trainer import train
        config = load_config(config_path, overrides=overrides)
        _check_environment(config)
        train(config)


if __name__ == "__main__":
    main()
