#!/usr/bin/env python3
"""Energy training pipeline: SFT → quality gate → RL → quality gate.

One command, one artifact directory, all phases orchestrated.

Usage:
    python campaigns/energy_pipeline.py
    python campaigns/energy_pipeline.py --artifact-dir runs/energy-001
    python campaigns/energy_pipeline.py --skip-sft --sft-checkpoint runs/energy-001/sft/checkpoint_step_60
    python campaigns/energy_pipeline.py --approved-export approved_candidate_exports/job-123/export.json
    python campaigns/energy_pipeline.py --dry-run

Prerequisites:
    1. Generate SFT data (if not already done):
       cargo run --release --bin soma_http -- configs/http/soma-energy-local.toml
       cd python && uv run python scripts/generate_sft_data_universal.py configs/sft/energy-search.toml

    2. Start the HTTP kernel for RL:
       cargo run --release --bin soma_http -- configs/http/soma-energy-local.toml

Artifact directory structure:
    {artifact_dir}/
    ├── pipeline.json        # full pipeline config + status + results
    ├── sft/                 # Phase 1: SFT checkpoints + logs
    │   ├── sft.toml
    │   ├── metrics.jsonl
    │   └── checkpoint_step_60/
    ├── bench-sft/           # Phase 2: SFT quality gate benchmark
    │   └── results.json
    ├── rl/                  # Phase 3: RL checkpoints + logs
    │   ├── rl.toml
    │   ├── metrics.jsonl
    │   └── checkpoint_step_*/
    └── bench-rl/            # Phase 4: RL quality gate benchmark
        └── results.json

Algorithm: REINFORCE++ with batch advantage normalization
  - Critic-free (same memory as GRPO)
  - Global batch normalization (fixes GRPO's biased local estimator)
  - Asymmetric clipping ε_low=0.2, ε_high=0.28 (DAPO clip-higher)
  - Per-turn rewards from energy domain (profit-based scoring)
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path


JSONDict = dict[str, object]


# ---------------------------------------------------------------------------
# Pipeline configuration
# ---------------------------------------------------------------------------

@dataclass
class PipelineConfig:
    """All knobs for the full energy pipeline in one place."""

    # -- Artifact --
    artifact_dir: str = ""  # auto-generated if empty

    # -- Backend --
    backend: str = "tinker"

    # -- Model --
    model: str = "Qwen/Qwen3-4B-Instruct-2507"
    lora_rank: int = 128

    # -- SFT phase --
    sft_steps: int = 60
    sft_lr: float = 4e-5
    sft_batch_size: int = 4
    sft_data_path: str = "/Users/teilomillet/Code/soma/python/data/sft/energy_search_sft.train.jsonl"

    # -- RL phase --
    rl_steps: int = 200
    rl_lr: float = 1e-5
    rl_batch_size: int = 4
    rl_group_size: int = 8
    rl_adv_clip_max: float = 5.0
    rl_temperature: float = 0.7

    # -- Environment (energy-specific) --
    http_url: str = "http://127.0.0.1:13737"
    max_turns: int = 120
    num_examples: int = 800
    dataset_seed: int = 7

    # Energy domain defaults
    grid_max_import_kw: float = 10.0
    utility_grid_export_limit_kw: float = 3.0
    forecast_demand_base_mape: float = 0.02
    forecast_demand_mape_per_step: float = 0.01
    forecast_solar_base_mape: float = 0.05
    forecast_solar_mape_per_step: float = 0.025
    horizon_ticks: int = 96

    # -- Benchmark --
    bench_seeds: list[int] = field(default_factory=lambda: [100, 200, 300])
    bench_max_turns: int = 2000

    # -- Quality gates --
    sft_gate_min_avg_score: float = 0.1  # normalized [0,1]

    # -- Tracking --
    wandb_project: str = ""
    wandb_entity: str = ""

    # -- Misc --
    seed: int = 42
    save_every: int = 20
    max_tokens: int = 10240
    approved_export_path: str = ""


# ---------------------------------------------------------------------------
# TOML generation
# ---------------------------------------------------------------------------

def _run_tag(cfg: PipelineConfig) -> str:
    ts = datetime.now().strftime("%m%d-%H%M")
    model_short = cfg.model.split("/")[-1][:12]
    return f"en-{model_short}-s{cfg.seed}-{ts}"


def _sft_toml(cfg: PipelineConfig, log_dir: str, run_tag: str) -> str:
    wandb_section = ""
    if cfg.wandb_project:
        wandb_section = f"""
wandb_project = "{cfg.wandb_project}"
wandb_run_name = "{run_tag}/sft"
wandb_group = "{run_tag}"
wandb_tags = "energy,sft,reinforce_pp,pipeline,{run_tag}"
"""
        if cfg.wandb_entity:
            wandb_section += f'wandb_entity = "{cfg.wandb_entity}"\n'

    return f"""\
# Auto-generated by energy_pipeline.py — Phase 1: SFT
[backend]
backend = "{cfg.backend}"

[model]
model = "{cfg.model}"
lora_rank = {cfg.lora_rank}

[algorithm]
advantage_mode = "reinforce_pp"
transform_mode = "none"

[training]
seed = {cfg.seed}
max_steps = {cfg.sft_steps}
sft_warmup_steps = {cfg.sft_steps}
sft_data_path = "{cfg.sft_data_path}"
batch_size = {cfg.sft_batch_size}
group_size = 16
max_tokens = {cfg.max_tokens}
temperature = 0.7
lr = {cfg.sft_lr}
save_every = {cfg.save_every}

[logging]
log_dir = "{log_dir}"
{wandb_section}"""


def _rl_toml(cfg: PipelineConfig, log_dir: str, run_tag: str) -> str:
    wandb_section = ""
    if cfg.wandb_project:
        wandb_section = f"""
wandb_project = "{cfg.wandb_project}"
wandb_run_name = "{run_tag}/rl"
wandb_group = "{run_tag}"
wandb_tags = "energy,rl,reinforce_pp,batch_norm,pipeline,{run_tag}"
"""
        if cfg.wandb_entity:
            wandb_section += f'wandb_entity = "{cfg.wandb_entity}"\n'

    return f"""\
# Auto-generated by energy_pipeline.py — Phase 2: RL (REINFORCE++)
[backend]
backend = "{cfg.backend}"

[model]
model = "{cfg.model}"
lora_rank = {cfg.lora_rank}

[algorithm]
advantage_mode = "reinforce_pp"
transform_mode = "none"

[training]
seed = {cfg.seed}
max_steps = {cfg.rl_steps}
sft_warmup_steps = 0
batch_size = {cfg.rl_batch_size}
group_size = {cfg.rl_group_size}
max_tokens = {cfg.max_tokens}
temperature = {cfg.rl_temperature}
lr = {cfg.rl_lr}
save_every = {cfg.save_every}
batch_advantage_norm = true
adv_clip_max = {cfg.rl_adv_clip_max}

[environment]
provider = "verifiers"
id = "soma_energy"
max_turns = {cfg.max_turns}

[environment.args]
num_examples = {cfg.num_examples}
dataset_seed = {cfg.dataset_seed}
max_turns = {cfg.max_turns}
http_url = "{cfg.http_url}"

[environment.args.default_config]
grid_max_import_kw = {cfg.grid_max_import_kw}
utility_grid_export_limit_kw = {cfg.utility_grid_export_limit_kw}
forecast_demand_base_mape = {cfg.forecast_demand_base_mape}
forecast_demand_mape_per_step = {cfg.forecast_demand_mape_per_step}
forecast_solar_base_mape = {cfg.forecast_solar_base_mape}
forecast_solar_mape_per_step = {cfg.forecast_solar_mape_per_step}

[environment.args.evaluator]
horizon_ticks = {cfg.horizon_ticks}

[logging]
log_dir = "{log_dir}"
{wandb_section}"""


# ---------------------------------------------------------------------------
# Phase runners
# ---------------------------------------------------------------------------

@dataclass
class PhaseResult:
    phase: str
    status: str  # "pass", "fail", "skip", "error"
    duration_s: float = 0.0
    details: dict = field(default_factory=dict)


def _run_retrain(toml_path: str, extra_args: list[str] | None = None) -> int:
    cmd = [sys.executable, "-m", "retrain", toml_path]
    if extra_args:
        cmd.extend(extra_args)
    print(f"  $ {' '.join(cmd)}")
    proc = subprocess.run(cmd, cwd=str(Path(__file__).resolve().parent.parent))
    return proc.returncode


def _find_last_checkpoint(log_dir: str) -> str | None:
    log_path = Path(log_dir)
    if not log_path.exists():
        return None
    checkpoints = sorted(
        log_path.glob("checkpoint_step_*"),
        key=lambda p: int(p.name.split("_")[-1]) if p.name.split("_")[-1].isdigit() else 0,
    )
    return str(checkpoints[-1]) if checkpoints else None


def _run_benchmark(
    model: str,
    seeds: list[int],
    http_url: str,
    max_turns: int,
    output_path: str,
    adapter_path: str | None = None,
) -> list[dict]:
    """Record benchmark config. Must be filled by running bench_energy.py manually."""
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    bench_config = {
        "model": model,
        "adapter_path": adapter_path,
        "seeds": seeds,
        "http_url": http_url,
        "max_turns": max_turns,
        "domain": "energy",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "status": "pending",
        "instructions": (
            "Run benchmark manually:\n"
            f"  uv run python python/scripts/bench_energy.py"
            + (f" --adapter {adapter_path}" if adapter_path else "")
            + f"\n  Results → {output_path}"
        ),
    }
    with open(output, "w") as f:
        json.dump(bench_config, f, indent=2)

    return []


def _check_sft_gate(
    bench_path: str,
    min_avg_score: float,
) -> tuple[bool, dict]:
    path = Path(bench_path)
    if not path.exists():
        return False, {"reason": "benchmark results not found", "path": bench_path}

    with open(path) as f:
        data = json.load(f)

    if data.get("status") == "pending":
        return False, {
            "reason": "benchmark not yet run — run it manually, then re-execute pipeline with --skip-sft",
            "instructions": data.get("instructions", ""),
        }

    results = data if isinstance(data, list) else data.get("results", [])
    if not results:
        return False, {"reason": "no benchmark results found"}

    avg_score = sum(r.get("score", 0) for r in results) / len(results)

    passed = avg_score >= min_avg_score
    details = {
        "total_seeds": len(results),
        "avg_score": round(avg_score, 4),
        "min_avg_score_required": min_avg_score,
        "passed": passed,
    }
    return passed, details


def _resolve_export_path(base_dir: Path, value: str) -> Path:
    path = Path(value).expanduser()
    if path.is_absolute():
        return path.resolve()
    return (base_dir / path).resolve()


def _load_approved_export_handoff(export_index_path: str | Path) -> tuple[Path, JSONDict]:
    path = Path(export_index_path).expanduser().resolve()
    if not path.exists():
        raise FileNotFoundError(f"approved export bundle not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"approved export bundle must be a JSON object: {path}")
    return path, data


def _apply_approved_export_handoff(
    cfg: PipelineConfig,
    export_index_path: str | Path,
) -> JSONDict:
    """Apply an approved export bundle to the retrain pipeline config."""
    path, export_bundle = _load_approved_export_handoff(export_index_path)

    domain = export_bundle.get("domain")
    if isinstance(domain, str) and domain.strip() and domain != "energy":
        raise ValueError(
            f"approved export bundle is for domain {domain!r}, not 'energy'"
        )

    retrain_input = export_bundle.get("retrain_input", {})
    if not isinstance(retrain_input, dict):
        retrain_input = {}

    candidate = export_bundle.get("candidate", {})
    if not isinstance(candidate, dict):
        candidate = {}

    candidate_model = candidate.get("model")
    if isinstance(candidate_model, str) and candidate_model.strip():
        cfg.model = candidate_model

    retrain_domain = retrain_input.get("domain")
    if isinstance(retrain_domain, str) and retrain_domain.strip() and retrain_domain != "energy":
        raise ValueError(
            f"approved export retrain input targets {retrain_domain!r}, not 'energy'"
        )

    sft_data_path = retrain_input.get("sft_data_path")
    if not isinstance(sft_data_path, str) or not sft_data_path.strip():
        raise ValueError("approved export bundle is missing retrain_input.sft_data_path")
    cfg.sft_data_path = str(_resolve_export_path(path.parent, sft_data_path))
    cfg.approved_export_path = str(path)

    export_id = export_bundle.get("export_id")
    if not isinstance(export_id, str) or not export_id.strip():
        export_id = path.stem
    if not cfg.artifact_dir:
        cfg.artifact_dir = str(path.parent / "retrain_runs" / export_id)

    return export_bundle


# ---------------------------------------------------------------------------
# Pipeline state
# ---------------------------------------------------------------------------

@dataclass
class PipelineState:
    config: dict = field(default_factory=dict)
    phases: list[dict] = field(default_factory=list)
    current_phase: str = "sft"
    sft_checkpoint: str = ""
    rl_checkpoint: str = ""
    started_at: str = ""
    finished_at: str = ""
    status: str = "running"

    def save(self, path: str) -> None:
        with open(path, "w") as f:
            json.dump(asdict(self), f, indent=2, default=str)

    @classmethod
    def load(cls, path: str) -> PipelineState:
        with open(path) as f:
            data = json.load(f)
        state = cls()
        for k, v in data.items():
            if hasattr(state, k):
                setattr(state, k, v)
        return state


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def run_pipeline(
    cfg: PipelineConfig,
    *,
    dry_run: bool = False,
    skip_sft: bool = False,
    sft_checkpoint: str = "",
) -> PipelineState:
    """Run the full energy training pipeline."""

    if not cfg.artifact_dir:
        ts = datetime.now().strftime("%Y%m%d-%H%M%S")
        cfg.artifact_dir = f"runs/energy-{ts}"

    art = Path(cfg.artifact_dir)
    art.mkdir(parents=True, exist_ok=True)

    state_path = str(art / "pipeline.json")

    if Path(state_path).exists():
        state = PipelineState.load(state_path)
        print(f"Resuming pipeline from phase: {state.current_phase}")
    else:
        state = PipelineState(
            config=asdict(cfg),
            started_at=datetime.now(timezone.utc).isoformat(),
        )

    sft_dir = str(art / "sft")
    rl_dir = str(art / "rl")
    bench_sft_path = str(art / "bench-sft" / "results.json")
    bench_rl_path = str(art / "bench-rl" / "results.json")

    run_tag = state.config.get("run_tag", "") if state.phases else ""
    if not run_tag:
        run_tag = _run_tag(cfg)
        state.config["run_tag"] = run_tag

    # Verify SFT data exists before starting
    sft_data = Path(cfg.sft_data_path)
    if not sft_data.exists() and not skip_sft:
        print(f"ERROR: SFT data not found at {cfg.sft_data_path}")
        print(f"\nGenerate it first:")
        print(f"  cargo run --release --bin soma_http -- configs/http/soma-energy-local.toml")
        print(f"  cd python && uv run python scripts/generate_sft_data_universal.py ../configs/sft/energy-search.toml")
        return PipelineState(status="failed")

    # Write manifest
    manifest_path = str(art / "manifest.json")
    if not Path(manifest_path).exists():
        manifest = {
            "pipeline": "energy",
            "run_tag": run_tag,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "config": asdict(cfg),
            "algorithm": {
                "name": "REINFORCE++ with Baseline",
                "paper": "arxiv:2501.03262",
                "advantage_mode": "reinforce_pp",
                "batch_advantage_norm": True,
                "evidence": [
                    "SFT-first optimal: Wang & Ammanabrolu (2510.01132)",
                    "REINFORCE++ > GRPO & PPO on agents: Hu (2501.03262)",
                    "No sigma normalization: ScaleRL, Dr. GRPO",
                ],
            },
            "phases": [
                {"name": "sft", "steps": cfg.sft_steps, "lr": cfg.sft_lr},
                {"name": "bench-sft", "gate": {"min_avg_score": cfg.sft_gate_min_avg_score}},
                {"name": "rl", "steps": cfg.rl_steps, "lr": cfg.rl_lr,
                 "batch_advantage_norm": True, "adv_clip_max": cfg.rl_adv_clip_max},
                {"name": "bench-rl"},
            ],
        }
        with open(manifest_path, "w") as f:
            json.dump(manifest, f, indent=2)

    print(f"\n{'='*70}")
    print(f"  ENERGY TRAINING PIPELINE")
    print(f"  Artifact: {cfg.artifact_dir}")
    print(f"  Run tag:  {run_tag}")
    print(f"  Model:    {cfg.model}")
    print(f"  Backend:  {cfg.backend}")
    if cfg.approved_export_path:
        print(f"  Export:   {cfg.approved_export_path}")
    print(f"  SFT:      {cfg.sft_steps} steps (lr={cfg.sft_lr})")
    print(f"  RL:       {cfg.rl_steps} steps (lr={cfg.rl_lr})")
    print(f"  Algorithm: REINFORCE++ + batch_advantage_norm")
    if cfg.wandb_project:
        print(f"  W&B:      {cfg.wandb_project} (group={run_tag})")
    print(f"{'='*70}\n")

    if dry_run:
        print("[DRY RUN] Would execute the following phases:\n")

    # ── Phase 1: SFT ──────────────────────────────────────────────────────
    if skip_sft or state.current_phase in ("bench-sft", "rl", "bench-rl", "done"):
        checkpoint = sft_checkpoint or state.sft_checkpoint
        if not checkpoint:
            print("ERROR: --skip-sft requires --sft-checkpoint")
            state.status = "failed"
            state.save(state_path)
            return state
        print(f"[Phase 1: SFT] SKIPPED — using checkpoint: {checkpoint}")
        state.sft_checkpoint = checkpoint
    else:
        print(f"[Phase 1: SFT] {cfg.sft_steps} steps on oracle demonstrations")
        sft_toml_path = str(art / "sft.toml")
        toml_content = _sft_toml(cfg, sft_dir, run_tag)

        if dry_run:
            print(f"  Would write: {sft_toml_path}")
            print(f"  Would run:   retrain {sft_toml_path}")
        else:
            Path(sft_toml_path).write_text(toml_content)
            t0 = time.time()
            rc = _run_retrain(sft_toml_path)
            duration = time.time() - t0

            if rc != 0:
                result = PhaseResult("sft", "error", duration, {"return_code": rc})
                state.phases.append(asdict(result))
                state.status = "failed"
                state.save(state_path)
                print(f"\n  SFT FAILED (exit code {rc})")
                return state

            checkpoint = _find_last_checkpoint(sft_dir)
            if not checkpoint:
                print(f"\n  ERROR: No checkpoint found in {sft_dir}")
                state.status = "failed"
                state.save(state_path)
                return state

            state.sft_checkpoint = checkpoint
            state.current_phase = "bench-sft"
            result = PhaseResult("sft", "pass", duration, {"checkpoint": checkpoint})
            state.phases.append(asdict(result))
            state.save(state_path)
            print(f"\n  SFT complete: {checkpoint} ({duration:.0f}s)")

    # ── Phase 2: SFT Quality Gate ─────────────────────────────────────────
    if state.current_phase in ("rl", "bench-rl", "done"):
        print(f"[Phase 2: SFT Quality Gate] SKIPPED — already passed")
    else:
        print(f"\n[Phase 2: SFT Quality Gate] Benchmark on seeds {cfg.bench_seeds}")

        if dry_run:
            print(f"  Would benchmark: {state.sft_checkpoint or '<pending>'}")
            print(f"  Would save to:   {bench_sft_path}")
            print(f"  Gate: avg score ≥{cfg.sft_gate_min_avg_score}")
        else:
            _run_benchmark(
                model=cfg.model,
                seeds=cfg.bench_seeds,
                http_url=cfg.http_url,
                max_turns=cfg.bench_max_turns,
                output_path=bench_sft_path,
                adapter_path=state.sft_checkpoint,
            )

            passed, details = _check_sft_gate(
                bench_sft_path,
                cfg.sft_gate_min_avg_score,
            )

            result = PhaseResult(
                "bench-sft",
                "pass" if passed else "paused",
                details=details,
            )
            state.phases.append(asdict(result))

            if not passed:
                state.status = "paused"
                state.current_phase = "bench-sft"
                state.save(state_path)
                print(f"\n  SFT Quality Gate: PAUSED")
                print(f"  {details.get('reason', 'Gate not passed')}")
                print(f"\n  Next steps:")
                print(f"  1. Run benchmark manually")
                print(f"  2. Save results to: {bench_sft_path}")
                print(f"  3. Re-run: python {__file__} --artifact-dir {cfg.artifact_dir}")
                return state

            state.current_phase = "rl"
            state.save(state_path)
            print(f"\n  SFT Quality Gate: PASSED {details}")

    # ── Phase 3: RL ───────────────────────────────────────────────────────
    if state.current_phase in ("bench-rl", "done"):
        print(f"[Phase 3: RL] SKIPPED — already complete")
    else:
        print(f"\n[Phase 3: RL] {cfg.rl_steps} steps with REINFORCE++ + batch norm")
        rl_toml_path = str(art / "rl.toml")
        toml_content = _rl_toml(cfg, rl_dir, run_tag)

        if dry_run:
            print(f"  Would write: {rl_toml_path}")
            print(f"  Would run:   retrain {rl_toml_path} --resume-from {state.sft_checkpoint or '<pending>'}")
        else:
            Path(rl_toml_path).write_text(toml_content)
            t0 = time.time()
            rc = _run_retrain(rl_toml_path, ["--resume-from", state.sft_checkpoint])
            duration = time.time() - t0

            if rc != 0:
                result = PhaseResult("rl", "error", duration, {"return_code": rc})
                state.phases.append(asdict(result))
                state.status = "failed"
                state.save(state_path)
                print(f"\n  RL FAILED (exit code {rc})")
                return state

            checkpoint = _find_last_checkpoint(rl_dir)
            state.rl_checkpoint = checkpoint or ""
            state.current_phase = "bench-rl"
            result = PhaseResult("rl", "pass", duration, {"checkpoint": checkpoint})
            state.phases.append(asdict(result))
            state.save(state_path)
            print(f"\n  RL complete: {checkpoint} ({duration:.0f}s)")

    # ── Phase 4: RL Quality Gate ──────────────────────────────────────────
    if state.current_phase == "done":
        print(f"[Phase 4: RL Quality Gate] SKIPPED — already complete")
    else:
        print(f"\n[Phase 4: RL Quality Gate] Benchmark on seeds {cfg.bench_seeds}")

        if dry_run:
            print(f"  Would benchmark: {state.rl_checkpoint or '<pending>'}")
            print(f"  Would compare:   SFT-only vs SFT+RL")
        else:
            _run_benchmark(
                model=cfg.model,
                seeds=cfg.bench_seeds,
                http_url=cfg.http_url,
                max_turns=cfg.bench_max_turns,
                output_path=bench_rl_path,
                adapter_path=state.rl_checkpoint,
            )

            result = PhaseResult("bench-rl", "pass", details={
                "sft_checkpoint": state.sft_checkpoint,
                "rl_checkpoint": state.rl_checkpoint,
            })
            state.phases.append(asdict(result))
            state.current_phase = "done"
            state.status = "completed"
            state.finished_at = datetime.now(timezone.utc).isoformat()
            state.save(state_path)

    # ── Summary ───────────────────────────────────────────────────────────
    print(f"\n{'='*70}")
    print(f"  PIPELINE {state.status.upper()}")
    print(f"  Artifact: {cfg.artifact_dir}")
    print(f"  Run tag:  {run_tag}")
    if state.sft_checkpoint:
        print(f"  SFT checkpoint: {state.sft_checkpoint}")
    if state.rl_checkpoint:
        print(f"  RL checkpoint:  {state.rl_checkpoint}")
    print()
    for p in state.phases:
        status_icon = {"pass": "+", "fail": "x", "error": "!", "paused": "~", "skip": "-"}.get(p["status"], "?")
        print(f"    [{status_icon}] {p['phase']}: {p['status']} ({p.get('duration_s', 0):.0f}s)")

    state.save(state_path)

    # Show artifact tree
    print(f"\n  Artifact tree:")
    for item in sorted(art.rglob("*")):
        if item.is_file() and ".git" not in str(item):
            rel = item.relative_to(art)
            size = item.stat().st_size
            if size > 1_000_000:
                size_str = f"{size / 1_000_000:.1f}MB"
            elif size > 1_000:
                size_str = f"{size / 1_000:.0f}KB"
            else:
                size_str = f"{size}B"
            print(f"    {rel}  ({size_str})")
    print(f"{'='*70}\n")

    return state


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Energy training pipeline: SFT → quality gate → RL → quality gate",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--artifact-dir", default="", help="Output directory (auto-generated if empty)")
    parser.add_argument("--backend", default="tinker", choices=["tinker", "local"])
    parser.add_argument("--model", default="Qwen/Qwen3-4B-Instruct-2507")
    parser.add_argument("--sft-steps", type=int, default=60)
    parser.add_argument("--rl-steps", type=int, default=200)
    parser.add_argument("--sft-lr", type=float, default=4e-5)
    parser.add_argument("--rl-lr", type=float, default=1e-5)
    parser.add_argument("--http-url", default="http://127.0.0.1:13737")
    parser.add_argument("--dry-run", action="store_true", help="Show what would run without executing")
    parser.add_argument("--skip-sft", action="store_true", help="Skip SFT phase, use existing checkpoint")
    parser.add_argument("--sft-checkpoint", default="", help="Path to SFT checkpoint (with --skip-sft)")
    parser.add_argument("--sft-data", default="", help="Override SFT data path")
    parser.add_argument(
        "--approved-export",
        default="",
        help="Path to an approved candidate export bundle (export.json)",
    )
    parser.add_argument("--lora-rank", type=int, default=128)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--wandb-project", default="", help="W&B project (empty=disabled)")
    parser.add_argument("--wandb-entity", default="")

    args = parser.parse_args()

    cfg = PipelineConfig(
        artifact_dir=args.artifact_dir,
        backend=args.backend,
        model=args.model,
        lora_rank=args.lora_rank,
        sft_steps=args.sft_steps,
        rl_steps=args.rl_steps,
        sft_lr=args.sft_lr,
        rl_lr=args.rl_lr,
        http_url=args.http_url,
        seed=args.seed,
        wandb_project=args.wandb_project,
        wandb_entity=args.wandb_entity,
    )

    if args.sft_data:
        cfg.sft_data_path = args.sft_data

    if args.approved_export:
        _apply_approved_export_handoff(cfg, args.approved_export)

    state = run_pipeline(
        cfg,
        dry_run=args.dry_run,
        skip_sft=args.skip_sft,
        sft_checkpoint=args.sft_checkpoint,
    )

    ok = state.status in ("completed", "paused") or (args.dry_run and state.status != "failed")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
