#!/usr/bin/env python3
"""Warehouse training pipeline: SFT → quality gate → RL → quality gate.

One command, one artifact directory, all phases orchestrated.

Usage:
    python campaigns/warehouse_pipeline.py
    python campaigns/warehouse_pipeline.py --artifact-dir runs/warehouse-001
    python campaigns/warehouse_pipeline.py --skip-sft --sft-checkpoint runs/warehouse-001/sft/checkpoint_step_60
    python campaigns/warehouse_pipeline.py --dry-run

Artifact directory structure:
    {artifact_dir}/
    ├── pipeline.json        # full pipeline config + status + results
    ├── sft/                 # Phase 1: SFT checkpoints + logs
    │   ├── sft.toml
    │   ├── metrics.jsonl
    │   └── checkpoint_step_60/
    ├── bench-sft/           # Phase 2: SFT quality gate benchmark
    │   └── results.json
    ├── rl/                  # Phase 3: RL checkpoints + logs
    │   ├── rl.toml
    │   ├── metrics.jsonl
    │   └── checkpoint_step_*/
    └── bench-rl/            # Phase 4: RL quality gate benchmark
        └── results.json

Algorithm: REINFORCE++ with batch advantage normalization
  - Critic-free (same memory as GRPO)
  - Global batch normalization (fixes GRPO's biased local estimator)
  - Asymmetric clipping ε_low=0.2, ε_high=0.28 (DAPO clip-higher)
  - Dense per-turn rewards from warehouse domain

Evidence base:
  - SFT-first: 60 demos + RL is optimal (Wang & Ammanabrolu, 2510.01132)
  - REINFORCE++ > GRPO and PPO on agent tasks (Hu, 2501.03262)
  - σ normalization hurts at scale (ScaleRL, DAPO, Dr. GRPO)
  - Asymmetric clipping prevents entropy collapse (DAPO)
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
import tomllib
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path


# ---------------------------------------------------------------------------
# Pipeline configuration
# ---------------------------------------------------------------------------

@dataclass
class PipelineConfig:
    """All knobs for the full pipeline in one place."""

    # -- Artifact --
    artifact_dir: str = ""  # auto-generated if empty

    # -- Backend --
    backend: str = "tinker"  # tinker (remote GPU) or local

    # -- Model --
    model: str = "Qwen/Qwen3-4B-Instruct-2507"
    lora_rank: int = 32

    # -- SFT phase --
    sft_steps: int = 60
    sft_lr: float = 4e-5
    sft_batch_size: int = 4
    sft_data_path: str = "/Users/teilomillet/Code/soma/python/scripts/warehouse_sft_data.jsonl"

    # -- RL phase --
    rl_steps: int = 200
    rl_lr: float = 1e-5
    rl_batch_size: int = 4
    rl_group_size: int = 8
    rl_adv_clip_max: float = 5.0
    rl_temperature: float = 0.7

    # -- Environment --
    http_url: str = "http://127.0.0.1:3000"
    max_turns: int = 15
    num_examples: int = 16
    dataset_seed: int = 42

    # -- Benchmark --
    # Eval seeds must NOT overlap with training seeds [42..57]
    bench_seeds: list[int] = field(default_factory=lambda: [100, 200, 300])
    bench_max_turns: int = 3000

    # -- Quality gates --
    sft_gate_min_profitable_seeds: int = 2  # out of len(bench_seeds)
    sft_gate_min_avg_score: float = 0.1     # normalized [0,1]

    # -- Tracking --
    wandb_project: str = ""  # empty = no wandb
    wandb_entity: str = ""

    # -- Misc --
    seed: int = 42
    save_every: int = 20
    max_tokens: int = 10240


# ---------------------------------------------------------------------------
# TOML generation
# ---------------------------------------------------------------------------

def _run_tag(cfg: PipelineConfig) -> str:
    """Short unique tag for this pipeline run."""
    ts = datetime.now().strftime("%m%d-%H%M")
    model_short = cfg.model.split("/")[-1][:12]
    return f"wh-{model_short}-s{cfg.seed}-{ts}"


def _sft_toml(cfg: PipelineConfig, log_dir: str, run_tag: str) -> str:
    wandb_section = ""
    if cfg.wandb_project:
        wandb_section = f"""
wandb_project = "{cfg.wandb_project}"
wandb_run_name = "{run_tag}/sft"
wandb_group = "{run_tag}"
wandb_tags = "warehouse,sft,reinforce_pp,pipeline,{run_tag}"
"""
        if cfg.wandb_entity:
            wandb_section += f'wandb_entity = "{cfg.wandb_entity}"\n'

    return f"""\
# Auto-generated by warehouse_pipeline.py — Phase 1: SFT
[backend]
backend = "{cfg.backend}"

[model]
model = "{cfg.model}"
lora_rank = {cfg.lora_rank}

[algorithm]
advantage_mode = "reinforce_pp"
transform_mode = "none"

[training]
seed = {cfg.seed}
max_steps = {cfg.sft_steps}
sft_warmup_steps = {cfg.sft_steps}
sft_data_path = "{cfg.sft_data_path}"
batch_size = {cfg.sft_batch_size}
group_size = 16
max_tokens = {cfg.max_tokens}
temperature = 0.7
lr = {cfg.sft_lr}
save_every = {cfg.save_every}

[logging]
log_dir = "{log_dir}"
{wandb_section}"""


def _rl_toml(cfg: PipelineConfig, log_dir: str, run_tag: str) -> str:
    wandb_section = ""
    if cfg.wandb_project:
        wandb_section = f"""
wandb_project = "{cfg.wandb_project}"
wandb_run_name = "{run_tag}/rl"
wandb_group = "{run_tag}"
wandb_tags = "warehouse,rl,reinforce_pp,batch_norm,pipeline,{run_tag}"
"""
        if cfg.wandb_entity:
            wandb_section += f'wandb_entity = "{cfg.wandb_entity}"\n'

    return f"""\
# Auto-generated by warehouse_pipeline.py — Phase 2: RL (REINFORCE++)
[backend]
backend = "{cfg.backend}"

[model]
model = "{cfg.model}"
lora_rank = {cfg.lora_rank}

[algorithm]
advantage_mode = "reinforce_pp"
transform_mode = "none"

[training]
seed = {cfg.seed}
max_steps = {cfg.rl_steps}
sft_warmup_steps = 0
batch_size = {cfg.rl_batch_size}
group_size = {cfg.rl_group_size}
max_tokens = {cfg.max_tokens}
temperature = {cfg.rl_temperature}
lr = {cfg.rl_lr}
save_every = {cfg.save_every}
batch_advantage_norm = true
adv_clip_max = {cfg.rl_adv_clip_max}

[environment]
provider = "verifiers"
id = "soma_warehouse"
max_turns = {cfg.max_turns}

[environment.args]
num_examples = {cfg.num_examples}
dataset_seed = {cfg.dataset_seed}
max_turns = {cfg.max_turns}
http_url = "{cfg.http_url}"

[logging]
log_dir = "{log_dir}"
{wandb_section}"""


# ---------------------------------------------------------------------------
# Phase runners
# ---------------------------------------------------------------------------

@dataclass
class PhaseResult:
    phase: str
    status: str  # "pass", "fail", "skip", "error"
    duration_s: float = 0.0
    details: dict = field(default_factory=dict)


def _run_retrain(toml_path: str, extra_args: list[str] | None = None) -> int:
    """Run `retrain <toml>` as subprocess, streaming output."""
    cmd = [sys.executable, "-m", "retrain", toml_path]
    if extra_args:
        cmd.extend(extra_args)
    print(f"  $ {' '.join(cmd)}")
    proc = subprocess.run(cmd, cwd=str(Path(__file__).resolve().parent.parent))
    return proc.returncode


def _find_last_checkpoint(log_dir: str) -> str | None:
    """Find the latest checkpoint_step_N directory."""
    log_path = Path(log_dir)
    if not log_path.exists():
        return None
    checkpoints = sorted(
        log_path.glob("checkpoint_step_*"),
        key=lambda p: int(p.name.split("_")[-1]) if p.name.split("_")[-1].isdigit() else 0,
    )
    return str(checkpoints[-1]) if checkpoints else None


def _run_benchmark(
    model: str,
    seeds: list[int],
    http_url: str,
    max_turns: int,
    output_path: str,
    adapter_path: str | None = None,
) -> list[dict]:
    """Run warehouse benchmark episodes and save results.

    This calls run_episode directly (no OpenRouter needed for local models).
    For local adapter evaluation, we'd need vLLM or similar serving.
    For now, we record the benchmark config and return placeholder results
    that must be filled by running bench_warehouse.py manually.
    """
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    bench_config = {
        "model": model,
        "adapter_path": adapter_path,
        "seeds": seeds,
        "http_url": http_url,
        "max_turns": max_turns,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "status": "pending",
        "instructions": (
            "Run benchmark manually:\n"
            f"  python python/scripts/bench_warehouse.py"
            + (f" --adapter {adapter_path}" if adapter_path else "")
            + f"\n  Results → {output_path}"
        ),
    }
    with open(output, "w") as f:
        json.dump(bench_config, f, indent=2)

    return []


def _check_sft_gate(
    bench_path: str,
    min_profitable: int,
    min_avg_score: float,
) -> tuple[bool, dict]:
    """Check SFT quality gate from benchmark results.

    Returns (passed, details).
    """
    path = Path(bench_path)
    if not path.exists():
        return False, {"reason": "benchmark results not found", "path": bench_path}

    with open(path) as f:
        data = json.load(f)

    if data.get("status") == "pending":
        return False, {
            "reason": "benchmark not yet run — run it manually, then re-execute pipeline with --skip-sft",
            "instructions": data.get("instructions", ""),
        }

    results = data if isinstance(data, list) else data.get("results", [])
    if not results:
        return False, {"reason": "no benchmark results found"}

    profitable = sum(1 for r in results if r.get("profit_euros", 0) > 0)
    avg_score = sum(r.get("score", 0) for r in results) / len(results)

    passed = profitable >= min_profitable and avg_score >= min_avg_score
    details = {
        "profitable_seeds": profitable,
        "total_seeds": len(results),
        "avg_score": round(avg_score, 4),
        "min_profitable_required": min_profitable,
        "min_avg_score_required": min_avg_score,
        "passed": passed,
    }
    return passed, details


# ---------------------------------------------------------------------------
# Pipeline state
# ---------------------------------------------------------------------------

@dataclass
class PipelineState:
    """Persisted pipeline state — survives restarts."""

    config: dict = field(default_factory=dict)
    phases: list[dict] = field(default_factory=list)
    current_phase: str = "sft"
    sft_checkpoint: str = ""
    rl_checkpoint: str = ""
    started_at: str = ""
    finished_at: str = ""
    status: str = "running"  # running, paused, completed, failed

    def save(self, path: str) -> None:
        with open(path, "w") as f:
            json.dump(asdict(self), f, indent=2, default=str)

    @classmethod
    def load(cls, path: str) -> PipelineState:
        with open(path) as f:
            data = json.load(f)
        state = cls()
        for k, v in data.items():
            if hasattr(state, k):
                setattr(state, k, v)
        return state


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def run_pipeline(
    cfg: PipelineConfig,
    *,
    dry_run: bool = False,
    skip_sft: bool = False,
    sft_checkpoint: str = "",
) -> PipelineState:
    """Run the full warehouse training pipeline."""

    # -- Resolve artifact directory --
    if not cfg.artifact_dir:
        ts = datetime.now().strftime("%Y%m%d-%H%M%S")
        cfg.artifact_dir = f"runs/warehouse-{ts}"

    art = Path(cfg.artifact_dir)
    art.mkdir(parents=True, exist_ok=True)

    state_path = str(art / "pipeline.json")

    # Resume if state exists
    if Path(state_path).exists():
        state = PipelineState.load(state_path)
        print(f"Resuming pipeline from phase: {state.current_phase}")
    else:
        state = PipelineState(
            config=asdict(cfg),
            started_at=datetime.now(timezone.utc).isoformat(),
        )

    sft_dir = str(art / "sft")
    rl_dir = str(art / "rl")
    bench_sft_path = str(art / "bench-sft" / "results.json")
    bench_rl_path = str(art / "bench-rl" / "results.json")

    # Generate a short run tag for wandb grouping
    run_tag = state.config.get("run_tag", "") if state.phases else ""
    if not run_tag:
        run_tag = _run_tag(cfg)
        state.config["run_tag"] = run_tag

    # Write manifest on first run
    manifest_path = str(art / "manifest.json")
    if not Path(manifest_path).exists():
        manifest = {
            "pipeline": "warehouse",
            "run_tag": run_tag,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "config": asdict(cfg),
            "algorithm": {
                "name": "REINFORCE++ with Baseline",
                "paper": "arxiv:2501.03262",
                "advantage_mode": "reinforce_pp",
                "batch_advantage_norm": True,
                "evidence": [
                    "SFT-first optimal: Wang & Ammanabrolu (2510.01132)",
                    "REINFORCE++ > GRPO & PPO on agents: Hu (2501.03262)",
                    "No sigma normalization: ScaleRL, Dr. GRPO",
                    "Turn-level advantages: TL-GRPO (2601.16480)",
                ],
            },
            "phases": [
                {"name": "sft", "steps": cfg.sft_steps, "lr": cfg.sft_lr},
                {"name": "bench-sft", "gate": {
                    "min_profitable_seeds": cfg.sft_gate_min_profitable_seeds,
                    "min_avg_score": cfg.sft_gate_min_avg_score,
                }},
                {"name": "rl", "steps": cfg.rl_steps, "lr": cfg.rl_lr,
                 "batch_advantage_norm": True, "adv_clip_max": cfg.rl_adv_clip_max},
                {"name": "bench-rl"},
            ],
            "artifacts": {
                "sft_config": "sft.toml",
                "sft_logs": "sft/",
                "sft_metrics": "sft/metrics.jsonl",
                "sft_generations": "sft/emergence/generations.jsonl",
                "sft_benchmark": "bench-sft/results.json",
                "rl_config": "rl.toml",
                "rl_logs": "rl/",
                "rl_metrics": "rl/metrics.jsonl",
                "rl_generations": "rl/emergence/generations.jsonl",
                "rl_benchmark": "bench-rl/results.json",
                "pipeline_state": "pipeline.json",
            },
        }
        with open(manifest_path, "w") as f:
            json.dump(manifest, f, indent=2)

    print(f"\n{'='*70}")
    print(f"  WAREHOUSE TRAINING PIPELINE")
    print(f"  Artifact: {cfg.artifact_dir}")
    print(f"  Run tag:  {run_tag}")
    print(f"  Model:    {cfg.model}")
    print(f"  Backend:  {cfg.backend}")
    print(f"  SFT:      {cfg.sft_steps} steps (lr={cfg.sft_lr})")
    print(f"  RL:       {cfg.rl_steps} steps (lr={cfg.rl_lr})")
    print(f"  Algorithm: REINFORCE++ + batch_advantage_norm")
    if cfg.wandb_project:
        print(f"  W&B:      {cfg.wandb_project} (group={run_tag})")
    print(f"{'='*70}\n")

    if dry_run:
        print("[DRY RUN] Would execute the following phases:\n")

    # ── Phase 1: SFT ──────────────────────────────────────────────────────
    if skip_sft or state.current_phase in ("bench-sft", "rl", "bench-rl", "done"):
        checkpoint = sft_checkpoint or state.sft_checkpoint
        if not checkpoint:
            print("ERROR: --skip-sft requires --sft-checkpoint")
            state.status = "failed"
            state.save(state_path)
            return state
        print(f"[Phase 1: SFT] SKIPPED — using checkpoint: {checkpoint}")
        state.sft_checkpoint = checkpoint
    else:
        print(f"[Phase 1: SFT] {cfg.sft_steps} steps on oracle demonstrations")
        sft_toml_path = str(art / "sft.toml")
        toml_content = _sft_toml(cfg, sft_dir, run_tag)

        if dry_run:
            print(f"  Would write: {sft_toml_path}")
            print(f"  Would run:   retrain {sft_toml_path}")
        else:
            Path(sft_toml_path).write_text(toml_content)
            t0 = time.time()
            rc = _run_retrain(sft_toml_path)
            duration = time.time() - t0

            if rc != 0:
                result = PhaseResult("sft", "error", duration, {"return_code": rc})
                state.phases.append(asdict(result))
                state.status = "failed"
                state.save(state_path)
                print(f"\n  SFT FAILED (exit code {rc})")
                return state

            checkpoint = _find_last_checkpoint(sft_dir)
            if not checkpoint:
                print(f"\n  ERROR: No checkpoint found in {sft_dir}")
                state.status = "failed"
                state.save(state_path)
                return state

            state.sft_checkpoint = checkpoint
            state.current_phase = "bench-sft"
            result = PhaseResult("sft", "pass", duration, {"checkpoint": checkpoint})
            state.phases.append(asdict(result))
            state.save(state_path)
            print(f"\n  SFT complete: {checkpoint} ({duration:.0f}s)")

    # ── Phase 2: SFT Quality Gate ─────────────────────────────────────────
    if state.current_phase in ("rl", "bench-rl", "done"):
        print(f"[Phase 2: SFT Quality Gate] SKIPPED — already passed")
    else:
        print(f"\n[Phase 2: SFT Quality Gate] Benchmark on seeds {cfg.bench_seeds}")

        if dry_run:
            print(f"  Would benchmark: {state.sft_checkpoint or '<pending>'}")
            print(f"  Would save to:   {bench_sft_path}")
            print(f"  Gate: ≥{cfg.sft_gate_min_profitable_seeds} profitable seeds, "
                  f"avg score ≥{cfg.sft_gate_min_avg_score}")
        else:
            _run_benchmark(
                model=cfg.model,
                seeds=cfg.bench_seeds,
                http_url=cfg.http_url,
                max_turns=cfg.bench_max_turns,
                output_path=bench_sft_path,
                adapter_path=state.sft_checkpoint,
            )

            passed, details = _check_sft_gate(
                bench_sft_path,
                cfg.sft_gate_min_profitable_seeds,
                cfg.sft_gate_min_avg_score,
            )

            result = PhaseResult(
                "bench-sft",
                "pass" if passed else "paused",
                details=details,
            )
            state.phases.append(asdict(result))

            if not passed:
                state.status = "paused"
                state.current_phase = "bench-sft"
                state.save(state_path)
                print(f"\n  SFT Quality Gate: PAUSED")
                print(f"  {details.get('reason', 'Gate not passed')}")
                print(f"\n  Next steps:")
                print(f"  1. Run benchmark: python python/scripts/bench_warehouse.py")
                print(f"  2. Save results to: {bench_sft_path}")
                print(f"  3. Re-run: python {__file__} --artifact-dir {cfg.artifact_dir}")
                return state

            state.current_phase = "rl"
            state.save(state_path)
            print(f"\n  SFT Quality Gate: PASSED {details}")

    # ── Phase 3: RL ───────────────────────────────────────────────────────
    if state.current_phase in ("bench-rl", "done"):
        print(f"[Phase 3: RL] SKIPPED — already complete")
    else:
        print(f"\n[Phase 3: RL] {cfg.rl_steps} steps with REINFORCE++ + batch norm")
        rl_toml_path = str(art / "rl.toml")
        toml_content = _rl_toml(cfg, rl_dir, run_tag)

        if dry_run:
            print(f"  Would write: {rl_toml_path}")
            print(f"  Would run:   retrain {rl_toml_path} --resume-from {state.sft_checkpoint or '<pending>'}")
        else:
            Path(rl_toml_path).write_text(toml_content)
            t0 = time.time()
            rc = _run_retrain(rl_toml_path, ["--resume-from", state.sft_checkpoint])
            duration = time.time() - t0

            if rc != 0:
                result = PhaseResult("rl", "error", duration, {"return_code": rc})
                state.phases.append(asdict(result))
                state.status = "failed"
                state.save(state_path)
                print(f"\n  RL FAILED (exit code {rc})")
                return state

            checkpoint = _find_last_checkpoint(rl_dir)
            state.rl_checkpoint = checkpoint or ""
            state.current_phase = "bench-rl"
            result = PhaseResult("rl", "pass", duration, {"checkpoint": checkpoint})
            state.phases.append(asdict(result))
            state.save(state_path)
            print(f"\n  RL complete: {checkpoint} ({duration:.0f}s)")

    # ── Phase 4: RL Quality Gate ──────────────────────────────────────────
    if state.current_phase == "done":
        print(f"[Phase 4: RL Quality Gate] SKIPPED — already complete")
    else:
        print(f"\n[Phase 4: RL Quality Gate] Benchmark on seeds {cfg.bench_seeds}")

        if dry_run:
            print(f"  Would benchmark: {state.rl_checkpoint or '<pending>'}")
            print(f"  Would compare:   SFT-only vs SFT+RL")
        else:
            _run_benchmark(
                model=cfg.model,
                seeds=cfg.bench_seeds,
                http_url=cfg.http_url,
                max_turns=cfg.bench_max_turns,
                output_path=bench_rl_path,
                adapter_path=state.rl_checkpoint,
            )

            result = PhaseResult("bench-rl", "pass", details={
                "sft_checkpoint": state.sft_checkpoint,
                "rl_checkpoint": state.rl_checkpoint,
            })
            state.phases.append(asdict(result))
            state.current_phase = "done"
            state.status = "completed"
            state.finished_at = datetime.now(timezone.utc).isoformat()
            state.save(state_path)

    # ── Summary ───────────────────────────────────────────────────────────
    print(f"\n{'='*70}")
    print(f"  PIPELINE {state.status.upper()}")
    print(f"  Artifact: {cfg.artifact_dir}")
    print(f"  Run tag:  {run_tag}")
    if state.sft_checkpoint:
        print(f"  SFT checkpoint: {state.sft_checkpoint}")
    if state.rl_checkpoint:
        print(f"  RL checkpoint:  {state.rl_checkpoint}")
    print()
    for p in state.phases:
        status_icon = {"pass": "+", "fail": "x", "error": "!", "paused": "~", "skip": "-"}.get(p["status"], "?")
        print(f"    [{status_icon}] {p['phase']}: {p['status']} ({p.get('duration_s', 0):.0f}s)")

    # Save state before printing tree (so pipeline.json appears in listing)
    state.save(state_path)

    # Show artifact tree
    print(f"\n  Artifact tree:")
    for item in sorted(art.rglob("*")):
        if item.is_file() and ".git" not in str(item):
            rel = item.relative_to(art)
            size = item.stat().st_size
            if size > 1_000_000:
                size_str = f"{size / 1_000_000:.1f}MB"
            elif size > 1_000:
                size_str = f"{size / 1_000:.0f}KB"
            else:
                size_str = f"{size}B"
            print(f"    {rel}  ({size_str})")
    print(f"{'='*70}\n")

    return state


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Warehouse training pipeline: SFT → quality gate → RL → quality gate",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--artifact-dir", default="", help="Output directory (auto-generated if empty)")
    parser.add_argument("--backend", default="tinker", choices=["tinker", "local"])
    parser.add_argument("--model", default="Qwen/Qwen3-4B-Instruct-2507")
    parser.add_argument("--sft-steps", type=int, default=60)
    parser.add_argument("--rl-steps", type=int, default=200)
    parser.add_argument("--sft-lr", type=float, default=4e-5)
    parser.add_argument("--rl-lr", type=float, default=1e-5)
    parser.add_argument("--http-url", default="http://127.0.0.1:3000")
    parser.add_argument("--dry-run", action="store_true", help="Show what would run without executing")
    parser.add_argument("--skip-sft", action="store_true", help="Skip SFT phase, use existing checkpoint")
    parser.add_argument("--sft-checkpoint", default="", help="Path to SFT checkpoint (with --skip-sft)")
    parser.add_argument("--lora-rank", type=int, default=32)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--wandb-project", default="", help="W&B project (empty=disabled)")
    parser.add_argument("--wandb-entity", default="")

    args = parser.parse_args()

    cfg = PipelineConfig(
        artifact_dir=args.artifact_dir,
        backend=args.backend,
        model=args.model,
        lora_rank=args.lora_rank,
        sft_steps=args.sft_steps,
        rl_steps=args.rl_steps,
        sft_lr=args.sft_lr,
        rl_lr=args.rl_lr,
        http_url=args.http_url,
        seed=args.seed,
        wandb_project=args.wandb_project,
        wandb_entity=args.wandb_entity,
    )

    state = run_pipeline(
        cfg,
        dry_run=args.dry_run,
        skip_sft=args.skip_sft,
        sft_checkpoint=args.sft_checkpoint,
    )

    ok = state.status in ("completed", "paused") or (args.dry_run and state.status != "failed")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
