"""Bundled TOML templates for `retrain init`."""

from __future__ import annotations


STARTER_TOML = """\
# retrain configuration — generated by `retrain init`
# Docs: docs/configuration.md

[model]
model = "Qwen/Qwen3-4B-Instruct-2507"
lora_rank = 32

[algorithm]
advantage_mode = "maxrl"     # grpo | maxrl | reinforce_pp | my_module.my_advantage
transform_mode = "gtpo_sepa" # none | gtpo | ... | my_module.make_transform_spec

[training]
seed = -1                    # -1 = no seed
max_steps = 100              # conservative default for first run
batch_size = 4               # conservative default for first run
group_size = 16
max_tokens = 10240
temperature = 0.7
lr = 4e-5
save_every = 20

[backend]
backend = "local"
adapter_path = "adapters/my_run"

[logging]
log_dir = "logs/train"
# wandb_project = ""         # uncomment to enable wandb + checkpoint artifacts
checkpoint_artifacts = "auto"
"""


QUICKSTART_TOML = """\
# retrain quickstart — 20-step smoke test
# Generated by `retrain init --template quickstart`

[model]
model = "Qwen/Qwen3-4B-Instruct-2507"
lora_rank = 32

[algorithm]
advantage_mode = "grpo"
transform_mode = "none"

[training]
seed = -1
max_steps = 20
batch_size = 2
group_size = 8
max_tokens = 1024            # smoke-test profile (non-default)
temperature = 0.7
lr = 4e-5
save_every = 0               # no checkpoints for a quick test

[backend]
backend = "local"
adapter_path = "adapters/quickstart"

[logging]
log_dir = "logs/quickstart"
"""

EXPERIMENT_TOML = """\
# retrain experiment — reproducible 500-step training run
# Generated by `retrain init --template experiment`

[model]
model = "Qwen/Qwen3-4B-Instruct-2507"
lora_rank = 32

[algorithm]
advantage_mode = "maxrl"
transform_mode = "gtpo_sepa"

[training]
seed = 42
max_steps = 500
batch_size = 8
group_size = 16
max_tokens = 10240
temperature = 0.7
lr = 4e-5
save_every = 50

[sepa]
steps = 500
schedule = "linear"
delay_steps = 50
correct_rate_gate = 0.1

[backend]
backend = "local"
adapter_path = "adapters/experiment"

[logging]
log_dir = "logs/experiment"
wandb_project = ""           # set your project name to enable wandb
checkpoint_artifacts = "auto"
"""

CAMPAIGN_TOML = """\
# retrain campaign — sweep across conditions and seeds
# Generated by `retrain init --template campaign`

[campaign]
seeds = [42, 101, 202, 303]
max_steps = 200

[[campaign.conditions]]
advantage_mode = "grpo"
transform_mode = "none"

[[campaign.conditions]]
advantage_mode = "maxrl"
transform_mode = "gtpo_sepa"

# Base config shared by all runs
[model]
model = "Qwen/Qwen3-4B-Instruct-2507"
lora_rank = 32

[training]
batch_size = 8
group_size = 16
max_tokens = 10240
temperature = 0.7
lr = 4e-5

[backend]
backend = "local"
adapter_path = "adapters/campaign"

[logging]
log_dir = "logs/campaign"
# wandb_project = ""         # uncomment to enable wandb + checkpoint artifacts
checkpoint_artifacts = "auto"
"""


INIT_TEMPLATES: dict[str, tuple[str, str]] = {
    "default": (STARTER_TOML, "retrain.toml"),
    "quickstart": (QUICKSTART_TOML, "retrain.toml"),
    "experiment": (EXPERIMENT_TOML, "retrain.toml"),
    "campaign": (CAMPAIGN_TOML, "campaign.toml"),
}
