"""
Shared data models for Retrain inference.
"""

from dataclasses import dataclass
from typing import Dict, Any, List, Optional
import torch


@dataclass
class RawRolloutData:
    """Raw rollout data generated by inference."""
    prompt: str
    response: str
    prompt_tokens: List[int]
    response_tokens: List[int]
    logprobs: Optional[torch.Tensor]
    episode_id: int
    rollout_idx: int
    environment_result: Optional[Dict[str, Any]] = None


@dataclass 
class GenerationResult:
    """Result from backend-specific generation."""
    response: str
    tokens: List[int]
    logprobs: Optional[torch.Tensor] = None
